[msg MSG0512_JUNPEI_011 [Junpei]]
[s][bup 5 1 65535 0]Yuka-tan went to borrow a notebook,[n]huh? She must be serious about[n]studying for the exams...[n][w][e]
[s]I guess I should study too...[n][w][e]
[s]...starting tomorrow.[n][w][e]
[s]C'mon, let's hit the arcade![n]I gotta take a breather...[n][w][e]

[sel MSG0512_JUNPEI_01_SELL top]
[s]"Sure."[e]
[s]"Nope."[e]

[msg MSG0512_JUNPEI_022 [Junpei]]
[s][bup 5 1 65535 0]Sweet! Let's go![n][w][e]

[msg MSG0512_JUNPEI_033 [Junpei]]
[s][bup 5 1 65535 0]Shoot, maybe next time then.[n][w][e]
