[msg SCR_MSG_PARAM_MIRYOKU1]
[s]> Your Charm seems to have[n]increased![n][w][e]

[msg SCR_MSG_PARAM_MIRYOKU2]
[s]> Your Charm went from "[f 2 4 0]"[n]to "[f 2 4 1]"![n][w][e]

[msg MSG0503_YUKARI_01 [Yukari]]
[s][bup 2 1 65535 0]I'm gonna go see a movie with my[n]friend later.[n][w][e]
[s]Although she's late... Hmm.[n]I wonder where she is...[n][w][e]

[msg MSG0719_YUKARI_01 [Yukari]]
[s][bup 2 1 65535 0]I came to pick out a new bathing[n]suit, but there's nothing that[n]interests me.[n][w][e]
[s][bup 2 4 65535 0]Although, I don't think it's this[n]shop's selection...[n][w][e]
[s]It could just be that I'm not up[n]for a new swimsuit at all.[n][w][e]

[msg MSG0728_YUKARI_01 [Yukari]]
[s][bup 2 1 65535 0]Akihiko-senpai acts a little[n]different when Ken-kun is around.[n][w][e]
[s]Have you noticed?[n][w][e]

[sel MSG0728_YUKARI_01_SEL top]
[s]"Yeah."[e]
[s]"No."[e]

[sel MSG0728_YUKARI_01_SEL_G top]
[s]"Yeah."[e]
[s]"Not at all..."[e]

[msg MSG0728_YUKARI_02 [Yukari]]
[s][bup 2 1 65535 0]I wonder why... Maybe he doesn't[n]get along well with kids.[n][w][e]
[s]If you ask me, Akihiko-san seems[n]pretty clumsy...[n][w][e]

[msg MSG0728_YUKARI_03 [Yukari]]
[s][bup 2 1 65535 0]You're so thick![n][w][e]
[s]You should pay more attention to[n]how people get along with each[n]other.[n][w][e]

[msg MSG0504_JUNPEI_01 [Junpei]]
[s][bup 5 1 65535 0]I came to catch a movie with my[n]bud, but he said he couldn't[n]make it...[n][w][e]
[s]So, that's today down the drain.[n]We're gonna try again tomorrow.[n][w][e]
[s]I always have the worst luck on[n]my days off...[n][w][e]

[msg MSG0505_JUNPEI_01 [Junpei]]
[s][bup 5 1 65535 0]I came to catch a movie with my bud.[n][w][e]
[s]But dude, no one's showed up yet.[n]Maybe I'm just early, but...[n][w][e]

[msg MSG0728_JUNPEI_01 [Junpei]]
[s][bup 5 1 65535 0]Ken really respects Akihiko-san.[n][w][e]
[s]I totally understand how he feels.[n]Dude, Akihiko-san won 16 straight[n]boxing matches.[n][w][e]
[s]If even I look up to the guy, then[n]kids must think he's a hero, you[n]know?[n][w][e]

[sel MSG0728_JUNPEI_01_SEL top]
[s]"I think so too."[e]
[s]"I don't think so."[e]

[sel MSG0728_JUNPEI_01_SEL_G top]
[s]"I think so too."[e]
[s]"You think so?"[e]

[msg MSG0728_JUNPEI_02 [Junpei]]
[s][bup 5 4 65535 0]A hero... You think we have what[n]it takes to be heroes?[n][w][e]

[msg MSG0728_JUNPEI_03 [Junpei]]
[s][bup 5 1 65535 0]Ahh, you just don't understand[n]a man's passion![n][w][e]

[msg MSG0730_JUNPEI_01 [Junpei]]
[s][bup 5 1 65535 0]Dude, isn't our group getting kinda[n]messed-up?[n][w][e]
[s]We got a Persona-using robot, and[n]now there's a Persona-using dog![n][w][e]
[s]What's next, man? A gorilla with[n]potential?[n][w][e]

[msg MSG0809_JUNPEI_01 [Junpei]]
[s][bup 5 2 65535 0]Check out the town, man. There's[n]no Lost or anything, and it's[n]so clean... Feels good, huh?[n][w][e]
[s][bup 5 4 65535 0]My brain, on the other hand, is all[n]junky and dirty, and it feels bad.[n][w][e]
[s]Stupid summer school... I can't[n]believe this...[n][w][e]

[msg MSG0719_FUUKA_01 [Fuuka]]
[s][bup 6 1 65535 0]I came to look at bathing suits[n]with Yukari-chan.[n][w][e]
[s]I've never bought a bathing suit[n]besides the school one.[n][w][e]
[s][bup 6 4 65535 0]But I don't think Yukari-chan is[n]really up for this...[n][w][e]

[msg MSG_NPC000_FST [Flower Shop Lady]]
[s]Welcome to Rafflesia.[n][w][e]
[s]What kind of flowers are you[n]looking for today?[n]        (Money: [clr 1][f 2 4 2] yen[clr 0])[n][w][e]

[msg MSG_NPC000_FST2 [Flower Shop Lady]]
[s]Would you like another type[n]of flower?[n]        (Money: [clr 1][f 2 4 2] yen[clr 0])[n][w][e]

[msg MSG_NPC000_2ND [柿蔚のお患さん]]
[s]乾於では衣に2印侃、嬰冠の寒臆柿を[n]セレクトして刊勘勧しております。[n][w][e]
[s]巻せて柿因喚と、それにちなんだ、[n]科々お堪いメッセージもお姦えします。[n][w][e]
[s]もしもお完劃の官けになったならば、[n]寛いな井です。[n][w][e]
[s]それでは干幹、刊勘勧しましょう。[n][w][e]

[sel MSG_NPC000_SEL top]
[s]Rose Bouquet[e]
[s]Red Pine Bonsai[e]
[s]Mini Cactus[e]
[s]Glass Vase[e]
[s]Never mind[e]

[msg MSG_NPC000_FLOWER [Flower Shop Lady]]
[s]It'll be [f 2 4 1] yen for [f 2 5 3 13 0].[n][w][e]

[sel MSG_NPC000_YESNO top]
[s]"Sure."[e]
[s]"On second thought..."[e]

[msg MSG_NPC000_THANKS [Flower Shop Lady]]
[s]Thank you very much for[n]your purchase.[n][w][e]
[s]> Obtained [f 2 5 3 13 0].[n][f 1 4][e]

[msg MSG_NPC000_BYE [Flower Shop Lady]]
[s]Please come again.[n][w][e]

[msg MSG_NPC000_DONTHAVE [Flower Shop Lady]]
[s]Hmm? You don't have enough space[n]for [f 2 5 3 13 0].[n][w][e]
[s]Come back once you've organized[n]your belongings.[n][w][e]

[msg MSG_NPC000_NOMONEY [Flower Shop Lady]]
[s]Hmm? You don't have enough money.[n][w][e]
[s]Save up, and come back again.[n][w][e]

[msg MSG_NPC000_GIRL [Flower Shop Lady]]
[s]Welcome to Rafflesia.[n][w][e]
[s]Oddly enough, we don't sell[n]Rafflesias here. Trust me.[n]You wouldn't want one.[n][w][e]

[msg MSG_4A_NPC001_01 [Station Attendant]]
[s]The best part of this station is its[n]size, and how close it is to the[n]ocean. We're proud of it.[n][w][e]
[s]I personally like it a lot...[n]What about you?[n][w][e]

[sel MSG_4A_NPC001_01_SEL top]
[s]"I love it."[e]
[s]"It's nothing special."[e]
[s]"I'm not a fan."[e]

[sel MSG_4A_NPC001_01_SEL_G top]
[s]"I love it."[e]
[s]"It's okay."[e]
[s]"I'm not a fan..."[e]

[msg MSG_4A_NPC001_02 [Station Attendant]]
[s]Wonderful! I'm glad you like it.[n][w][e]

[msg MSG_4A_NPC001_03 [Station Attendant]]
[s]Well, the more often you come here,[n]the more it'll grow on you.[n][w][e]

[msg MSG_4A_NPC001_04 [Station Attendant]]
[s]I see... I'm a little disappointed[n]to hear you don't grasp the beauty[n]of this station.[n][w][e]

[msg MSG_4B_NPC001_01 [Station Attendant]]
[s]This station plaza has a modern[n]design, and space for many different[n]stores.[n][w][e]
[s]Please abide by the station rules,[n]and refrain from littering.[n][w][e]
[s]I'm the one who has to clean it...[n][w][e]

[msg MSG_0501_NPC001_01 [Station Attendant]]
[s]There are lots of weird people[n]out there now... I heard it's the[n]Apathy Syndrome victims, but...[n][w][e]
[s]They keep walking in front of the[n]trains, and stopping them from[n]moving.[n][w][e]
[s]I'd hate to see one of them jump[n]in front of a moving train...[n][w][e]

[msg MSG_5A_NPC001_01 [Station Attendant]]
[s]Even I don't understand what's going[n]on here.[n][w][e]
[s]Right at the stroke of midnight,[n]that train appeared right behind[n]the other one.[n][w][e]
[s]Huh? You're glad there wasn't an[n]accident? You kids are so naive,[n]I'm jealous...[n][w][e]
[s]Because of this incident, the[n]company's stock went down...[n]And my salary went down with it.[n][w][e]
[s]If I ever find the culprit, I'm[n]going to throw him from the train[n]into the ocean![n][w][e]

[msg MSG_5B_NPC001_01 [Station Attendant]]
[s]Recently... this girl has started[n]coming around here...[n][w][e]
[s]She wears this white dress, with[n]this puffy lace...[n][w][e]
[s]I don't know what kind of fashion[n]that is, but... it's not my style.[n][w][e]

[msg MSG_6A_NPC001_01 [Station Attendant]]
[s]If you go down the side street,[n]you'll come to a spot where[n]gangs gather.[n][w][e]
[s]They always leave garbage behind,[n]and spray graffiti all over the[n]walls.[n][w][e]
[s]And every time, I'm the one who[n]has to clean it up.[n][w][e]
[s]I'm going to catch those gangs[n]someday and make them clean it[n]up themselves...[n][w][e]

[msg MSG_6B_NPC001_01 [Station Attendant]]
[s]Every year during the rainy season,[n]a lot of umbrellas are left in the[n]lost and found.[n][w][e]
[s]The lost and found box is full[n]almost instantly, and I have to[n]take care of it, and...[n][w][e]
[s]Rainy days are depressing.[n][w][e]

[msg MSG_7A_NPC001_01 [Station Attendant]]
[s]This station is near the high[n]school, so I often spot Gekkoukan[n]students and their friends.[n][w][e]
[s]You seem to be alone a lot...[n]Do you have any friends?[n][w][e]

[sel MSG_7A_NPC001_01_SEL top]
[s]"I have plenty."[e]
[s]"I wish I did, but..."[e]
[s]"I don't need friends."[e]

[sel MSG_7A_NPC001_01_SEL_G top]
[s]"Of course!"[e]
[s]"I wish I did, but..."[e]
[s]"No, I don't..."[e]

[msg MSG_7A_NPC001_02 [Station Attendant]]
[s]Great! I... I wish I'd had some[n]friends when I was in school.[n][w][e]

[msg MSG_7A_NPC001_03 [Station Attendant]]
[s]I suggest you make friends now.[n]The longer you wait in life, the[n]harder it'll be.[n][w][e]

[msg MSG_7A_NPC001_04 [Station Attendant]]
[s]Well, that's depressing. Do what[n]you want, I suppose...[n][w][e]

[msg MSG_7A_NPC001_04_G [Station Attendant]]
[s]Well, that's depressing. Now's your best[n]chance to try and make some![n][w][e]

[msg MSG_7B_NPC001_01 [Station Attendant]]
[s]This couple started a fight the[n]other day with a bouquet of[n]flowers...[n][w][e]
[s]Just like in the movies, the girl[n]was whacking the guy over and over[n]with the bouquet.[n][w][e]
[s]Now I get nervous every time I see[n]someone buy a bouquet down there,[n]and then walk over here...[n][w][e]

[msg MSG_8A_NPC001_01 [Station Attendant]]
[s]During summer vacation, this place[n]is so quiet, since there aren't any[n]students rushing onto the train.[n][w][e]
[s]I like the quiet...[n][w][e]

[msg MSG_8B_NPC001_01 [Station Attendant]]
[s]There's always more trouble around[n]that spot during summer vacation...[n][w][e]
[s]Well, whatever they do, I just don't[n]want them to do it over here.[n][w][e]
[s]As long as they stay on their side,[n]I don't give a damn what they do.[n][w][e]

[msg MSG_9A_NPC001_01 [Station Attendant]]
[s]School started again... The students[n]have been fun to watch this term.[n][w][e]
[s]All those people trying to look[n]good after vacation, who can't[n]pull it off...[n][w][e]
[s]Inside, I just smile at them and[n]laugh.[n][w][e]

[msg MSG_9B_NPC001_01 [Station Attendant]]
[s]There's a giant typhoon approaching,[n]it seems.[n][w][e]
[s]If the rain gets too strong, the[n]railways will be shut down, so[n]please keep that in mind.[n][w][e]
[s]Though I don't think anyone would[n]go out in that kind of weather...[n][w][e]
[s]I know I don't want to come to[n]work, on days like that.[n][w][e]

[msg MSG_10A_NPC001_01 [Station Attendant]]
[s]The other day, I saw a young man who[n]was... a little different.[n][w][e]
[s]He seemed about the age to be in high[n]school, and he was throwing a ball[n]up and down.[n][w][e]
[s]Do high school students still play[n]with those kinds of toys?[n][w][e]
[s]Well, I heard people's mental states[n]were in decline, so maybe so...[n][w][e]

[msg MSG_0927_NPC001_01 [Station Attendant]]
[s]I know you've heard it before, but[n]there seem to be more of those[n]people all the time.[n][w][e]
[s]I'm just worried they'll stop the[n]trains, or something terrible.[n][w][e]

[msg MSG_10B_NPC001_01 [Station Attendant]]
[s]A Gekkoukan student was killed,[n]huh...?[n][w][e]
[s]So those gangs at the spot are[n]capable of murder...[n][w][e]
[s]*sigh*[n]It's dangerous, being a station[n]attendant...[n][w][e]

[msg MSG_10B_NPC001_01_G [Station Attendant]]
[s]A Gekkoukan student is in critical[n]condition, huh...?[n][w][e]
[s]Those gangs at the hideout are seriously[n]out of control...[n][w][e]
[s]*sigh* It's dangerous, being a station[n]attendant...[n][w][e]

[msg MSG_11A_NPC001_01 [Station Attendant]]
[s]After that incident, a lot of[n]customers have been going over[n]to that spot to take a peek.[n][w][e]
[s]Well, I don't blame them.[n][w][e]
[s]Who knows? Any of us might be the[n]next victim of gang violence.[n][w][e]
[s]I'm feeling worried myself...[n][w][e]

[msg MSG_11A_NPC001_01_G [Station Attendant]]
[s]After that incident, a lot of[n]customers have been going over[n]to that spot to take a peek.[n][w][e]
[s]Well, I don't blame them.[n][w][e]
[s]Who knows? Any of us might be the[n]next victim of gang violence.[n][w][e]
[s]I'm feeling worried myself...[n][w][e]

[msg MSG_11B_NPC001_01 [Station Attendant]]
[s]I was surprised to hear about[n]Mr. Kirijo.[n][w][e]
[s]Since the Kirijo Group has a stake[n]in this company, I'm worried about[n]the future.[n][w][e]
[s]Though to tell you the truth, as[n]long as I don't lose my job, I don't[n]really care what happens.[n][w][e]

[msg MSG_12A_NPC001_01 [Station Attendant]]
[s]Those people in town are like[n]statues.[n][w][e]
[s]Though, since they don't stop the[n]trains or cause any trouble...[n][w][e]
[s]I prefer them to the gangs at[n]that spot.[n][w][e]

[msg MSG_12B_NPC001_01 [Station Attendant]]
[s]I run into more couples during the[n]end of the year, compared to the[n]beginning of the year.[n][w][e]
[s]You got anyone you like to spend[n]time with?[n][w][e]

[sel MSG_12B_NPC001_01_SEL top]
[s]"Yeah, I've got a girl."[e]
[s]"I'll hook up eventually."[e]
[s]"I'm a loner."[e]

[sel MSG_12B_NPC001_01_SEL_G top]
[s]"Yes, I've got someone."[e]
[s]"I've got girl friends."[e]
[s]"Umm..."[e]

[msg MSG_12B_NPC001_02 [Station Attendant]]
[s]Good for you![n][w][e]
[s]Me, I'm a loner...[n][w][e]

[msg MSG_12B_NPC001_03 [Station Attendant]]
[s]You should get on it now. Time[n]waits for no man![n][w][e]

[msg MSG_12B_NPC001_03_G [Station Attendant]]
[s]So you like to have fun with your[n]female friends? Women are so lucky...[n][w][e]

[msg MSG_12B_NPC001_04 [Station Attendant]]
[s]Wow, that's a surprise. I didn't[n]think there were any left...[n]Well, do what you will.[n][w][e]

[msg MSG_12B_NPC001_04_G [Station Attendant]]
[s]Oh... I shouldn't have asked that.[n]Sorry.[n][w][e]

[msg MSG_1A_NPC001_01 [Station Attendant]]
[s]People's manners are getting even[n]worse these days.[n][w][e]
[s]They litter, argue, fight, and[n]people are starting to get hurt.[n][w][e]
[s]And I'm the one who has to field[n]all the complaints as a result.[n][w][e]
[s]It's getting on my nerves...[n][w][e]

[msg MSG_1B_NPC001_01 [Station Attendant]]
[s]People's manners aren't very good[n]anymore. The train and the plaza[n]are both filthy.[n][w][e]
[s]Everything around me gets worse[n]and worse... I don't know if it'll[n]return to normal anymore.[n][w][e]

[sel MSG_1B_NPC001_01_SEL top]
[s]"Of course it will."[e]
[s]"Me neither..."[e]

[sel MSG_1B_NPC001_01_SEL_G top]
[s]"Of course it will."[e]
[s]"Me neither..."[e]

[msg MSG_1B_NPC001_02 [Station Attendant]]
[s]You think so? What makes you[n]say that?[n][w][e]
[s]Well, maybe I shouldn't be so[n]downhearted.[n][w][e]

[msg MSG_1B_NPC001_03 [Station Attendant]]
[s]You either, huh? I tell you,[n]I can't take this anymore...[n][w][e]
[s]I should quit my job and start[n]following that cult.[n][w][e]

[msg MSG_3A_NPC001_01 [Station Attendant]]
[s]Oh yeah, those Apathy Syndrome[n]people disappeared.[n][w][e]
[s]I wonder why...[n][w][e]
[s]Well, I don't really care, as long[n]as the trains run on time.[n][w][e]

[msg MSG_4A_NPC002_01 [Man]]
[s]Do you like movies?[n][w][e]

[msg MSG_4A_NPC002_01_G [Man]]
[s]Do you like movies?[n][w][e]

[sel MSG_4A_NPC002_01_SEL top]
[s]"I love movies."[e]
[s]"I don't like movies."[e]

[sel MSG_4A_NPC002_01_SEL_G top]
[s]"I love movies."[e]
[s]"I don't like movies."[e]

[msg MSG_4A_NPC002_02 [Man]]
[s]Me, too! Movies kick ass![n][w][e]
[s]I love them because they're like[n]a microcosm of real life.[n][w][e]

[msg MSG_4A_NPC002_03 [Man]]
[s]Man, that's sad... You're going[n]to regret not seeing lots of[n]movies, later in life.[n][w][e]

[msg MSG_4B_NPC002_01 [Man]]
[s]That girl next to the vending[n]machine... She looks so sad,[n]doesn't she?[n][w][e]
[s]I get sad, too, after I've paid for[n]a crappy movie, but...[n][w][e]
[s]Not like that. That's just nuts.[n][w][e]
[s]Is this what people keep talking[n]about? That Apathy Syndrome...?[n][w][e]

[msg MSG_5A_NPC002_01 [Man]]
[s]All these new movies were released[n]during Golden Week, but...[n][w][e]
[s]They all sucked![n][w][e]
[s]I'm sure everyone else who wasted[n]their money on those turkeys is[n]saying the same thing.[n][w][e]

[msg MSG_5B_NPC002_01 [Man]]
[s]The monorail was nearly in a big[n]accident the other day. I heard it[n]was just a few feet away.[n][w][e]
[s]It's just like one of those action[n]thrillers, you know?[n][w][e]
[s]Whoever stopped that train is[n]a real-life hero![n][w][e]

[msg MSG_0602_NPC002_01 [Man]]
[s]You know those incidents where[n]people turn into Apathy Syndrome[n]victims, right?[n][w][e]
[s]Those guys look so weird... They're[n]all over town.[n][w][e]
[s]If it was a sci-fi movie, they'd[n]be zombies, and if it was a suspense[n]movie, it might be a virus...[n][w][e]
[s]But it's real life, and I have no[n]idea what's happening.[n][w][e]

[msg MSG_6A_NPC002_01 [Man]]
[s]I sometimes see this girl sitting[n]right over there, drawing.[n][w][e]
[s]She has red hair and a white, frilled[n]dress... She stands out like a sore[n]thumb.[n][w][e]
[s]I can't just walk by and pretend[n]like she's not there...[n][w][e]
[s]It's like some anime... You don't[n]usually see stuff like this. Maybe[n]I should talk to her next time...[n][w][e]

[msg MSG_6B_NPC002_01 [Man]]
[s]You know how in movies, you see[n]bodyguards with tattoos on their[n]arms, and you know they're badass?[n][w][e]
[s]Well, I saw one of 'em. It was right[n]near here.[n][w][e]
[s]He wasn't built like a bodyguard,[n]though...[n][w][e]
[s]He was rail-thin... It was easy to[n]tell, 'cause he wasn't wearing a shirt.[n][w][e]

[msg MSG_7A_NPC002_01 [Man]]
[s]You know how in movies, you see[n]bodyguards with tattoos on their[n]arms, and you know they're badass?[n][w][e]
[s]Well, I saw one of 'em. It was right[n]near here.[n][w][e]
[s]He wasn't built like a bodyguard,[n]though...[n][w][e]
[s]He was rail-thin... It was easy to[n]tell, 'cause he wasn't wearing a shirt.[n][w][e]

[msg MSG_7B_NPC002_01 [Man]]
[s]A movie's theme song is very[n]important.[n][w][e]
[s]The quality of the movie is greatly[n]affected by whether its theme song[n]is any good or not.[n][w][e]
[s]Which reminds me... Long ago,[n]I heard there was going to be[n]a Gekkoukan theme song.[n][w][e]
[s]I think it was called "Gekkoukan[n]Boogie," or something like that.[n]I heard it was nearly done.[n][w][e]
[s]I want to hear how it turned out,[n]but I wouldn't want a traditional[n]song for a theme...[n][w][e]

[msg MSG_8A_NPC002_01 [Man]]
[s]When you hear locust sound effects[n]on a show or a movie, doesn't it[n]remind you of summer?[n][w][e]
[s]Did you know they usually cut the[n]locust sounds out when exporting[n]movies or TV to other countries?[n][w][e]
[s]In places with no locusts, when they[n]hear that sound, they think it's[n]just static or white noise.[n][w][e]

[msg MSG_8B_NPC002_01 [Man]]
[s]Here's a question for you![n][w][e]
[s]Why do you think I'm so reluctant[n]to catch movies at the theater[n]during the summer?[n][w][e]

[sel MSG_8B_NPC002_01_SEL top]
[s]"It's cold inside."[e]
[s]"Summer blockbusters suck."[e]
[s]"Profits are receding."[e]
[s]"The owner's going bald."[e]

[msg MSG_8B_NPC002_02 [Man]]
[s]Got it in one shot! They blast the air[n]conditioner all day in there![n][w][e]
[s]I have to wear extra layers,[n]even in hot summers like this.[n][w][e]

[msg MSG_8B_NPC002_03 [Man]]
[s]Well, that's true sometimes, but[n]it doesn't really have to do with[n]summertime.[n][w][e]

[msg MSG_8B_NPC002_04 [Man]]
[s]How would I know!? That's a[n]terrible joke...[n][w][e]
[s]If this place goes out of business,[n]I don't have anywhere else to go![n][w][e]

[msg MSG_8B_NPC002_04_G [Man]]
[s]Like I give a damn about that![n]That's not funny, you know...[n][w][e]
[s]If this place goes out of business,[n]I don't have anywhere else to go![n][w][e]

[msg MSG_8B_NPC002_05 [Man]]
[s]Who cares...?[n][w][e]
[s]And who is this manager anyways!?[n]I'm here all the time, but I've[n]never seen him before![n][w][e]

[msg MSG_8B_NPC002_05_G [Man]]
[s]Who cares...?[n][w][e]
[s]And who is this manager anyways!?[n]I'm here all the time, but I've[n]never seen him before![n][w][e]

[msg MSG_0829_NPC002_01 [Man]]
[s]Man, there are more and more of[n]those people... But I'm getting[n]used to them now.[n][w][e]
[s]All they do is say "Ahh," and[n]"Uhhh," but they don't do anything.[n][w][e]
[s]I think it'd be cool if they[n]started attacking us, like one[n]of those horror movies.[n][w][e]

[msg MSG_9A_NPC002_01 [Man]]
[s]It's September, and it's time for[n]a new term. Did you get any transfer[n]students?[n][w][e]

[msg MSG_9A_NPC002_01_G [Man]]
[s]It's September, and it's time for[n]a new term. Did you get any transfer[n]students?[n][w][e]

[sel MSG_9A_NPC002_01_SEL top]
[s]"Yeah."[e]
[s]"No."[e]

[sel MSG_9A_NPC002_01_SEL_G top]
[s]"Yes."[e]
[s]"Nope."[e]

[msg MSG_9A_NPC002_02 [Man]]
[s]I'm jealous... Your school life[n]is just like a teen movie.[n][w][e]
[s]You're a lucky kid. Go enjoy[n]school while you can.[n][w][e]

[msg MSG_9A_NPC002_02_G [Man]]
[s]I'm jealous... Your school life[n]is just like a teen movie.[n][w][e]
[s]You're a lucky girl. Go enjoy[n]school while you can.[n][w][e]

[msg MSG_9A_NPC002_03 [Man]]
[s]I thought not. Transfer students[n]are usually pretty rare.[n][w][e]

[msg MSG_9B_NPC002_01 [Man]]
[s]Popcorn is great while watching[n]a movie, but I don't really eat[n]the stuff.[n][w][e]
[s]After all, if you're eating, you[n]can't be totally focused on the[n]movie you're watching.[n][w][e]
[s]Huh...? You can't concentrate if[n]you're hungry?[n][w][e]
[s]Ah, but that's when you need the[n]moviegoing spirit! My passion for[n]movies can overcome any hunger![n][w][e]
[s]Seriously![n][w][e]

[msg MSG_10A_NPC002_01 [Man]]
[s]Man, wasn't that typhoon nuts?[n][w][e]
[s]If it was just a movie typhoon,[n]I'd be all cheering for the special[n]effects and stuff...[n][w][e]
[s]In real life, it wasn't very[n]awesome. I give it one star.[n][w][e]

[msg MSG_10B_NPC002_01 [Man]]
[s]I understand kids fighting, but[n]murder is going too far.[n][w][e]
[s]They make social dramas about this[n]kind of thing, but...[n][w][e]
[s]I never thought it would happen[n]around here.[n][w][e]

[msg MSG_10B_NPC002_01_G [Man]]
[s]Sure, kids fight sometime, but it goes[n]too far when someone ends up nearly dead.[n][w][e]
[s]They make social dramas about this[n]kind of thing, but...[n][w][e]
[s]I never thought it would happen[n]around here.[n][w][e]

[msg MSG_11A_NPC002_01 [Man]]
[s]It's the time of year when school[n]couples come out to the movies[n]together.[n][w][e]
[s]But what they don't know is that[n]this thriller has a love-story[n]twist at the end![n][w][e]
[s]Man, you should see the expressions[n]on their faces as they come out![n][w][e]
[s]I almost bust a gut laughing at[n]it all! Heheheh![n][w][e]

[msg MSG_11B_NPC002_01 [Man]]
[s]Gekkoukan's chairman died from[n]falling from the observatory...[n][w][e]
[s]Usually, it's the bad guys who[n]tend to die by falling from a[n]high place, but...[n][w][e]
[s]That can't be right. I guess I've[n]been watching too many movies.[n][w][e]
[s]I should be praying for him...[n][w][e]

[msg MSG_12A_NPC002_01 [Man]]
[s]I heard the Gekkoukan class trip[n]was the other day. School life...[n]I get a little jealous.[n][w][e]
[s]It puts me in the mood to watch[n]those teenybopper love flicks.[n][w][e]
[s]*sigh*[n]Whatever happened to that genre of[n]movies, anyway...?[n][w][e]

[msg MSG_12B_NPC002_01 [Man]]
[s]It's that time of the year when[n]there's nothing but reruns on TV.[n][w][e]
[s]But reruns aren't so bad, man.[n][w][e]
[s]They make you nostalgic for your[n]younger days, you know?[n][w][e]

[msg MSG_1A_NPC002_01 [Man]]
[s]What would you do if the world was[n]going to end?[n][w][e]
[s]I would just have fun, man. I mean,[n]we're talking about lowering the[n]curtain on all life.[n][w][e]
[s]I imagine it saying "THE END," in[n]big letters, and then outtakes[n]from my life.[n][w][e]
[s]If you think about it that way, it[n]sounds a lot more fun, right?[n][w][e]

[msg MSG_1B_NPC002_01 [Man]]
[s]Sorry, man, but I don't believe in[n]that cult stuff.[n][w][e]
[s]"Nyx is coming down"? I mean, what[n]the hell, you know? There's only one[n]thing that comes from the skies...[n][w][e]
[s]You know it! UFOs! When it comes to[n]invasions from above, accept no[n]substitutes![n][w][e]

[msg MSG_3A_NPC002_01 [Man]]
[s]That was some weird crap about[n]a month ago, huh?[n][w][e]
[s]I don't know why, but all those[n]people were outside at midnight...[n][w][e]
[s]What were they all doing?[n][w][e]
[s]It was pretty cool, though...[n]Like the climactic scene of a movie.[n][w][e]

[msg MSG_4A_NPC003_01 [Male Student]]
[s]Man, school has started...[n]I'm so lazy.[n][w][e]
[s]Why? Listen, I don't need a reason[n]to be lazy. Besides, everyone gets[n]like this after days off.[n][w][e]
[s]It's the truth, man.[n][w][e]

[msg MSG_7A_NPC003_01 [Male Student]]
[s]I heard some guy made friends with[n]the workers, but isn't that a waste[n]of time?[n][w][e]
[s]I'm comfortable being the guy's[n]customer. I don't need to be his[n]friend, too, you know?[n][w][e]
[s]I mean, I'm sure there's an upside[n]to it, but... I'll pass anyway.[n][w][e]
[s]Too much trouble...[n][w][e]

[msg MSG_0701_NPC003_01 [Male Student]]
[s]Dude, check this out. There's lazy[n]people all over.[n][w][e]
[s]What's going through their minds?[n]Nothing, I guess...[n][w][e]
[s]I'm so jealous, man. I wanna be[n]just like them.[n][w][e]
[s]I'm already naturally lazy, so I've[n]got a head start on achieving total[n]blankness of mind![n][w][e]

[msg MSG_8A_NPC003_01 [Male Student]]
[s]You sure see a lot of couples during[n]summer vacation, huh?[n][w][e]
[s]Maybe I should get a girlfriend...[n]It's a lot of trouble, though.[n][w][e]
[s]Like just now, I saw a couple having[n]an argument, and the girl was like...[n][w][e]
[s]"I'm gonna report you to that revenge[n]website!"[n][w][e]
[s]...What was she talking about?[n][w][e]

[msg MSG_8A_NPC003_01_G [Male Student]]
[s]You sure see a lot of couples during[n]summer vacation, huh?[n][w][e]
[s]Maybe I should get a girlfriend...[n]It's a lot of trouble, though.[n][w][e]
[s]Like just now, I saw a couple having[n]an argument, and the girl was like...[n][w][e]
[s]"I'm gonna report you to that revenge[n]website!"[n][w][e]
[s]...What was she talking about?[n][w][e]

[msg MSG_9A_NPC003_01 [Male Student]]
[s]*sigh*[n]I'm feeling incredibly lazy...[n][w][e]
[s]Guess why...[n][w][e]

[sel MSG_9A_NPC003_01_SEL top]
[s]"Second term started?"[e]
[s]"Is it the heat?"[e]
[s]"You have Apathy Syndrome?"[e]
[s]"No clue."[e]

[msg MSG_9A_NPC003_02 [Male Student]]
[s]Yep. You know me, man.[n][w][e]

[msg MSG_9A_NPC003_03 [Male Student]]
[s]Well, that too.[n][w][e]
[s]But it's mainly 'cause I'm still[n]stuck in summer vacation mode...[n][w][e]

[msg MSG_9A_NPC003_04 [Male Student]]
[s]Aww, c'mon. I'm not that bad.[n][w][e]

[msg MSG_9A_NPC003_05 [Male Student]]
[s]Sheesh, way to kill the mood.[n]Now I feel even lazier...[n][w][e]

[msg MSG_10B_NPC003_01 [Male Student]]
[s]That Shinjiro guy got into trouble at[n]the gang hideout, right?[n][w][e]
[s]Sometimes I'll aimlessly wander[n]around there, but...[n][w][e]
[s]I should quit doing that.[n][w][e]

[msg MSG_1A_NPC003_01 [Male Student]]
[s]The people who believe in the End[n]have at least some energy left...[n][w][e]
[s]I mean, they have enough in them[n]to believe in something, y'know?[n][w][e]
[s]I don't even have that much, man.[n]It's over for me.[n][w][e]

[msg MSG_3A_NPC003_01 [Male Student]]
[s]Studying is so much work...[n][w][e]
[s]But there's this college I really[n]want to get into, so...[n][w][e]
[s]I guess I'll make the effort.[n][w][e]
[s]Just a little, anyway.[n][w][e]

[msg MSG_4A_NPC004_01 [Man]]
[s]Th-The weather is nice today...[n][w][e]

[msg MSG_4A_NPC005_01 [Woman]]
[s]Yeah. It is, isn't it?[n][w][e]

[msg MSG_4B_NPC004_01 [Man]]
[s]Hmmm... The conversation ended[n]so soon...[n][w][e]

[msg MSG_4B_NPC005_01 [Woman]]
[s]He looks like an interesting[n]guy, but he's a really bad[n]conversationalist.[n][w][e]
[s]I'm a little worried about him,[n]since this is the time of year[n]to make new friends.[n][w][e]

[msg MSG_5A_NPC004_01 [Man]]
[s]Should I talk about the club...?[n][w][e]
[s]No, that's no good... I already[n]did that...[n][w][e]

[msg MSG_5A_NPC005_01 [Woman]]
[s]My boyfriend plays soccer at his[n]college. I guess my taste in men[n]is pretty standard...[n][w][e]
[s]He's not that good at soccer,[n]though. He's still a third-stringer.[n][w][e]
[s]Don't you go to Gekkoukan? Are you[n]in any clubs?[n][w][e]

[sel MSG_5A_NPC005_01_SEL top]
[s]"Yeah, I'm in a club."[e]
[s]"No, I haven't joined any."[e]

[msg MSG_5A_NPC005_02 [Woman]]
[s]Good luck, then.[n][w][e]

[msg MSG_5A_NPC005_03 [Woman]]
[s]Well, it all depends on your[n]personal taste.[n][w][e]
[s]You get to meet more people, though,[n]if you join a club.[n][w][e]

[msg MSG_5B_NPC004_01 [Man]]
[s]H-How's your club going?[n][w][e]

[msg MSG_5B_NPC005_01 [Woman]]
[s]Eh, not bad.[n][w][e]

[msg MSG_6A_NPC004_01 [Man]]
[s]D-Do you think I could become[n]a first-stringer...?[n][w][e]

[msg MSG_6A_NPC005_01 [Woman]]
[s]Sure. If you work hard, I think[n]you can make it.[n][w][e]

[msg MSG_6B_NPC004_01 [Man]]
[s]Gotta find something to talk[n]about... But what...?[n][w][e]

[msg MSG_6B_NPC005_01 [Woman]]
[s]He's really overthinking this.[n]He looks suave, but he worries[n]what other people think too much.[n][w][e]
[s]I mean, I love that he cares about[n]my opinion, but...[n][w][e]
[s]I think I'd prefer it if he didn't[n]feel so nervous in front of me.[n][w][e]

[msg MSG_7A_NPC004_01 [Man]]
[s]I-It's getting hot outside, huh?[n][w][e]

[msg MSG_7A_NPC005_01 [Woman]]
[s]Yeah. Summer's almost here.[n][w][e]

[msg MSG_7B_NPC004_01 [Man]]
[s]The conversation died again...[n]I keep sweating...[n][w][e]
[s]Is it because of the heat, or is[n]this a cold sweat...?[n][w][e]

[msg MSG_7B_NPC005_01 [Woman]]
[s]He's sweating a lot now, but he's[n]usually not like that.[n][w][e]
[s]That type of guy is pretty popular[n]with the older ladies who work here.[n][w][e]
[s]Everyone remembers his face. I was[n]surprised, to be honest.[n][w][e]
[s]It's amazing how many people say[n]hello to him at shops...[n][w][e]

[msg MSG_8A_NPC004_01 [Man]]
[s]T-The weather is nice... The sky[n]is blue, and there's a cool[n]breeze...[n][w][e]

[msg MSG_8A_NPC005_01 [Woman]]
[s]Yeah. The sky's pretty.[n][w][e]

[msg MSG_0731_NPC004_01 [Man]]
[s]Th-There are a lot of weirdos...[n]It's creepy, huh...?[n][w][e]

[msg MSG_0731_NPC005_01 [Woman]]
[s]Yeah, it's creepy.[n][w][e]

[msg MSG_8B_NPC004_01 [Man]]
[s]The beach... She's asking me to[n]go to the beach...?[n][w][e]
[s]How did this happen? Am I really[n]allowed to go...?[n][w][e]

[msg MSG_8B_NPC005_01 [Woman]]
[s]He's a sweet guy, but he seems to[n]be holding back. It's like he won't[n]allow himself to enjoy life.[n][w][e]
[s]Even after his friend and[n]I offered to take him to the beach.[n][w][e]
[s]He just keeps turning us down,[n]over and over... He'll never[n]have fun that way.[n][w][e]
[s]But I won't leave him. Don't get me[n]wrong.[n][w][e]

[msg MSG_9A_NPC004_01 [Man]]
[s]W-We couldn't go to the beach,[n]but... How about the mountains?[n][w][e]
[s]I-It'll be autumn pretty soon,[n]so the leaves will turn red...[n][w][e]

[msg MSG_9A_NPC005_01 [Woman]]
[s]Yeah, that'll be nice.[n][w][e]

[msg MSG_9B_NPC004_01 [Man]]
[s]Why am I like this...? How many[n]months has it been with her?[n][w][e]

[msg MSG_9B_NPC005_01 [Woman]]
[s]It's that time of the year, huh?[n][w][e]
[s]Do you have a girlfriend? I bet you[n]could get one if you tried.[n][w][e]
[s]You can do it! Just find someone[n]you're interested in, and talk[n]to her.[n][w][e]
[s]Even he managed to do it, so you[n]should have no problem.[n][w][e]

[msg MSG_9B_NPC005_01_G [Woman]]
[s]It's that time of the year, huh?[n][w][e]
[s]Do you have a boyfriend? I bet you[n]could get one if you tried.[n][w][e]
[s]You can do it![n][w][e]
[s]I'm sure you'll find a wonderful[n]boyfriend![n][w][e]

[msg MSG_10A_NPC004_01 [Man]]
[s]Th-Thanks for looking at my[n]report...[n][w][e]
[s]I-I'd like to take you to...[n][w][e]
[s]No, wait! I-I take that ba--[n][w][e]

[msg MSG_10A_NPC005_01 [Woman]]
[s]Sure! Anywhere is fine with me.[n][w][e]

[msg MSG_10B_NPC004_01 [Man]]
[s]"What's more important to you,[n]soccer or me?" A-A question like[n]that...![n][w][e]
[s]She must be unhappy with me...[n][w][e]
[s]But why...? Is she really...?[n][w][e]

[msg MSG_10B_NPC005_01 [Woman]]
[s]That guy is just the type to take[n]a question like that seriously.[n][w][e]
[s]I was just testing him, though...[n][w][e]
[s]But I think you'd do fine in[n]a situation like that.[n][w][e]
[s]It's a trick we use to get the guy[n]closer to us.[n][w][e]

[msg MSG_10B_NPC005_01_G [Woman]]
[s]That guy is just the type to take[n]a question like that seriously.[n][w][e]
[s]I was just testing him, though...[n][w][e]
[s]I think it'd work pretty well for[n]you, too.[n][w][e]
[s]What do I mean? I'm talking about the[n]trick we use to get a guy interested.[n][w][e]

[msg MSG_11A_NPC004_01 [Man]]
[s]I-It's getting cold, huh?[n]It's almost winter...[n][w][e]

[msg MSG_11A_NPC005_01 [Woman]]
[s]Yeah, it's almost winter.[n][w][e]

[msg MSG_1027_NPC004_01 [Man]]
[s]I asked her on a date, but she said[n]no, saying she didn't want to go[n]to town...[n][w][e]
[s]Is it because it's getting cold, or[n]is it something I did...?[n][w][e]
[s]Argh... I don't know...![n][w][e]

[msg MSG_11B_NPC004_01 [Man]]
[s]Going to the mountains...? Did[n]I really say that?[n][w][e]
[s]But to really get the mountain[n]experience, we'll need two days[n]and one night at a hotel...[n][w][e]
[s]I mean, no! No no no! We've got[n]to get back before sunset..![n][w][e]

[msg MSG_11B_NPC005_01 [Woman]]
[s]Since we couldn't go to the beach[n]this summer, he suggested we go[n]to the mountains instead.[n][w][e]
[s]So I reminded him, and, well...[n][w][e]
[s]He got like this. It's so like[n]him...[n][w][e]

[msg MSG_12A_NPC004_01 [Man]]
[s]I-It's cold...[n][w][e]
[s]L-Let's hold hands or something...[n][w][e]
[s]N-Nothing! Forget about what[n]I just said![n][w][e]

[msg MSG_12A_NPC005_01 [Woman]]
[s]I was about to tell him, "Okay,"[n]but...[n][w][e]
[s]All of a sudden, he pulled his[n]hand away.[n][w][e]
[s]Did I do something wrong...?[n][w][e]

[msg MSG_12B_NPC004_01 [Man]]
[s]*sigh*[n]What was I thinking...?[n][w][e]
[s]Even if it seemed like a good[n]chance, I can't believe I actually[n]said that...[n][w][e]
[s]But I can't let things stay the way[n]they are forever...[n][w][e]

[msg MSG_12B_NPC005_01 [Woman]]
[s]Love won't blossom if you just[n]wait for it to happen.[n][w][e]
[s]If you want to get to know someone[n]better, you have to be more[n]aggressive.[n][w][e]
[s]He's a straightforward type, right?[n]So our relationship hasn't grown[n]even a little.[n][w][e]
[s]But I don't mind, really...[n][w][e]

[msg MSG_1A_NPC004_01 [Man]]
[s]I feel really awkward these days...[n][w][e]
[s]*sigh*...[n]I'm getting worried...[n][w][e]
[s]Is she okay...? She looks like this[n]kind of thing happens to her every[n]day...[n][w][e]

[msg MSG_1A_NPC005_01 [Woman]]
[s]It sounds preachy to talk about[n]moral stuff like this, but this[n]is when people's bonds are tested.[n][w][e]
[s]At times like this, when the whole[n]town is going crazy, and there's[n]nowhere to run...[n][w][e]
[s]I'm thankful he's here with me.[n][w][e]
[s]What about you? Do you have anyone[n]that will stay with you?[n][w][e]

[msg MSG_1B_NPC004_01 [Man]]
[s]I'm really worried...[n][w][e]
[s]We're spending so much time[n]together, it seems like it[n]has to end...[n][w][e]
[s]It's just me, right...?[n][w][e]

[msg MSG_1B_NPC005_01 [Woman]]
[s]Yeah, it's just you.[n][w][e]
[s]This will never end...[n][w][e]

[msg MSG_3A_NPC004_01 [Man]]
[s]It's been one year, huh...?[n]That was fast...[n][w][e]
[s]Nothing's really happened with[n]us in that year...[n][w][e]
[s]*sigh*[n][w][e]

[msg MSG_3A_NPC005_01 [Woman]]
[s]The year went by quickly.[n][w][e]
[s]It's true that nothing's changed[n]during the year, but I'm not too[n]worried about that.[n][w][e]
[s]He's just a straightforward kind[n]of guy, and that's the way I like[n]him![n][w][e]

[msg MSG_NORACAT [Woman]]
[s]Meow.[n][w][e]

[msg MSG_CHIDORI]
[s]> She's completely preoccupied with[n]her drawing...[n][w][e]

[msg MSG_9A_NPC015_01 [Male Student]]
[s]Dude, what's going on? That girl[n]who's been following me all this[n]time...[n][w][e]
[s]I was gonna talk to her, but she[n]stopped following me.[n][w][e]
[s]I've been watching her to try to[n]figure out what's going on, but this[n]seems kind of weird...[n][w][e]

[msg MSG_9A_NPC016_01 [Female Student]]
[s]Hmm... It feels like someone's[n]watching me...[n][w][e]
[s]Is it just me...?[n][w][e]

[msg MSG_11A_NPC015_01 [Male Student]]
[s]Dude, did you see that?[n][w][e]
[s]She helped the cat that those[n]brats were picking on![n][w][e]
[s]Then she fed it some real[n]high-class, gourmet cat food![n][w][e]
[s]It's just a stray cat. Why's she[n]making such a fuss over it...?[n][w][e]

[msg MSG_11A_NPC016_01 [Female Student]]
[s]God! This guy following me around[n]just won't quit![n][w][e]
[s]He must be one stubborn guy to[n]follow anyone around that much.[n][w][e]
[s]He'd make a great detective...[n][w][e]

[msg MSG_6A_NPC017_01 [Man]]
[s]I heard about the disaster from[n]someone I know who works at[n]Gekkoukan High.[n][w][e]

[sel MSG_6A_NPC017_01_SEL top]
[s]"Yeah?"[e]
[s]"What disaster?"[e]

[sel MSG_6A_NPC017_01_SEL_G top]
[s]"Oh really?"[e]
[s]"What disaster?"[e]

[msg MSG_6A_NPC017_02 [Man]]
[s]I think it's awful the way those[n]students are falling victim to[n]Apathy Syndrome.[n][w][e]
[s]It's probably because of all the[n]excess studying.[n][w][e]
[s]Why would they study so hard...?[n][w][e]
[s]I hope they don't have delusions of[n]going to a famous university, and[n]getting a high-powered job...[n][w][e]

[msg MSG_6A_NPC017_03 [Man]]
[s]Wow, I admire your bravery.[n][w][e]
[s]That's the spirit! Whatever happens[n]around you, just don't give a damn[n]about it.[n][w][e]
[s]An attitude like that will come in[n]handy once you enter adult society.[n][w][e]

[msg MSG_8B_NPC017_01 [Man]]
[s]I sometimes see a girl drawing here.[n][w][e]
[s]She looks a little strange,[n]but that's okay.[n][w][e]
[s]She's so mysterious... it's like she[n]lives in a different world.[n][w][e]
[s]She doesn't care what other people[n]say, she's living on her own, not[n]following anyone's orders...[n][w][e]
[s]As a salaryman who follows orders for[n]a living, I'm naturally jealous...[n][w][e]

[msg MSG_12A_NPC017_01 [Man]]
[s]Ouch... It still hurts.[n][w][e]

[sel MSG_12A_NPC017_01_SEL top]
[s]"Are you all right?"[e]
[s]"What happened?"[e]

[sel MSG_12A_NPC017_01_SEL_G top]
[s]"Are you all right?"[e]
[s]"What happened?"[e]

[msg MSG_12A_NPC017_02 [Man]]
[s]Thanks for your concern... You're[n]a nice kid, unlike the brats I saw[n]earlier...[n][w][e]

[msg MSG_12A_NPC017_03 [Man]]
[s]I was a little tipsy yesterday[n]at midnight, and ended up at the[n]gang spot.[n][w][e]
[s]I thought kids were too cool to[n]steal from middle-aged men now...[n][w][e]
[s]But they beat me until I could[n]barely talk anymore.[n][w][e]
[s]What kind of society is so vicious[n]to its weaker element? I feel like[n]I've lost the will to live...[n][w][e]

[msg MSG_5A_NPC018_01 [Woman]]
[s]Asking around is the basic technique[n]to gathering information, no matter[n]how creepy the story is.[n][w][e]
[s]So, how about it? Got any info[n]on the mysterious incident?[n][w][e]

[msg MSG_5A_NPC018_01_G [Woman]]
[s]Asking around is the basic technique[n]to gathering information, no matter[n]how creepy the story is.[n][w][e]
[s]So, how about it? Got any info[n]on the mysterious incident?[n][w][e]

[sel MSG_5A_NPC018_01_SEL top]
[s]"I don't know anything."[e]
[s]"Who are you...?"[e]
[s]"...Please leave me alone."[e]

[sel MSG_5A_NPC018_01_SEL_G top]
[s]"I don't know anything."[e]
[s]"Who are you...?"[e]
[s]"...Please leave me alone."[e]

[msg MSG_5A_NPC018_02 [Woman]]
[s]I see... How disappointing.[n][w][e]
[s]You've got a mysterious aura about[n]you, so I thought you might know[n]something about all this.[n][w][e]

[msg MSG_5A_NPC018_02_G [Woman]]
[s]I see... How disappointing.[n][w][e]
[s]My gut instinct told me you might know[n]something about all this.[n][w][e]

[msg MSG_5A_NPC018_03 [Woman]]
[s]Can't you tell by looking at me?[n]I'm a lady journalist.[n][w][e]
[s]I'm trying to bust this incident[n]wide open for the public.[n][w][e]

[msg MSG_5A_NPC018_04 [Woman]]
[s]......[n][w][e]
[s]> The woman smiles tightly...[n][f 1 4][e]

[msg MSG_7A_NPC018_01 [Woman]]
[s]The victims of Apathy Syndrome[n]can never get their normal lives[n]back...[n][w][e]
[s]Is that true or not?[n][w][e]

[sel MSG_7A_NPC018_01_SEL top]
[s]"That's true."[e]
[s]"That's BS."[e]

[msg MSG_7A_NPC018_02 [Woman]]
[s]That's what a lot of people think,[n]but it's not true.[n][w][e]

[msg MSG_7A_NPC018_03 [Woman]]
[s]You got it![n][w][e]

[msg MSG_7A_NPC018_04 [Woman]]
[s]The symptoms of the syndrome vary[n]from person to person, according to[n]my hard-won information.[n][w][e]
[s]Unconsciousness, loss of vitality,[n]aphasia, mental decline...[n][w][e]
[s]However, some only have minor[n]symptoms, and are back to a normal[n]life already.[n][w][e]

[msg MSG_9A_NPC018_01 [Woman]]
[s]Interviewers can't rely only on[n]primary sources. Eyewitness reports[n]are important, too.[n][w][e]
[s]My favorite part of gathering[n]information is all the unique[n]people I get to meet.[n][w][e]
[s]For example, the other day I talked[n]to a young man who spoke in Kansai[n]dialect.[n][w][e]
[s]Kansai isn't something you hear every[n]day around here![n][w][e]

[msg MSG_1105_NPC018_01 [Woman]]
[s]Hmmm... Strange. The victims from[n]that incident aren't going away...[n][w][e]
[s]Usually they disappear after the[n]full moon, but...[n][w][e]
[s]Maybe something's changed, and[n]I didn't notice?[n][w][e]
[s]Well, whatever it is, it doesn't[n]seem good...[n][w][e]

[msg MSG_11A_NPC018_01 [Woman]]
[s]Mr. Kirijo passed away. Officially,[n]it was from an illness, but...[n][w][e]
[s]I'd be no reporter if I just[n]believed the official story![n][w][e]
[s]There's something going on here...[n]I heard a rumor that it might have[n]been murder.[n][w][e]

[msg MSG_1A_NPC018_01 [Woman]]
[s]There was a magazine profile on[n]the founder of that cult.[n][w][e]
[s]But I don't think it's worth all[n]the attention...[n][w][e]
[s]It's just a little club that those[n]kids made up.[n][w][e]
[s]Right?[n][w][e]

[msg MSG_1A_NPC019_01 [Woman]]
[s]These posters and paints are far[n]from meaningless for us.[n][w][e]
[s]By our acts, we will change the[n]flow of causality...[n][w][e]
[s]The concept of Salvation will be[n]in greater harmony with the earth,[n]tipping the scales to Deliverance.[n][w][e]
[s]The earth, seeking salvation, will[n]become an empty vessel for Nyx-sama[n]to fill.[n][w][e]

[msg MSG_1B_NPC019_01 [Woman]]
[s]Soon, Mother Nyx will descend from[n]the heavens, bringing the great[n]Deliverance.[n][w][e]
[s]It will be the greatest single[n]act of salvation that mankind has[n]ever witnessed.[n][w][e]
[s]We humans, trapped in our earthly[n]forms, will be embraced in Nyx's[n]arms...[n][w][e]
[s]We will sleep soundlessly and dream[n]forever, a dream of all beings[n]melted into one form...[n][w][e]
[s]This form will shatter to pieces[n]in Nyx's crucible, bringing about[n]our salvation.[n][w][e]

[msg MSG_1A_NPC021_01 [Man]]
[s]Sheesh, that lady's nuts.[n][w][e]
[s]I don't get what she's saying at[n]all. Maybe she's got brain damage?[n][w][e]
[s]Though I'm a believer too, so[n]I'm not really one to talk.[n][w][e]

[msg MSG_1A_NPC022_01 [Female Student]]
[s]I asked her what all those papers[n]and paintings mean...[n][w][e]
[s]And she started spouting all that[n]nonsense... It sounds like a lecture[n]or something.[n][w][e]
[s]I believe in the Deliverance, and[n]the End, and all that, but I still[n]can't follow what she's saying...[n][w][e]

[msg MSG_0809_NPC024_01 [Man]]
[s]There's a bar by the gang spot[n]with the best cocktails around.[n][w][e]
[s]But now they're looking into making[n]non-alcoholic cocktails.[n][w][e]
[s]It used to be a bar where adults[n]could drink in peace... Now it'll[n]be swarming with kids.[n][w][e]

[msg MSG_0906_NPC024_01 [Man]]
[s]There's a mahjong club at the[n]gang spot, and one of the guys[n]there is a mahjong demon.[n][w][e]
[s]He said "Let me test my luck," and[n]challenged me to a mahjong duel.[n][w][e]
[s]I came pretty close, man...[n][w][e]
[s]If I'd gotten the "Peacock,"[n]I could've beat the guy...[n][w][e]

[msg MSG_KAGE_01_01 [Male Student]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_01_02 [Male Student]]
[s]......[n][w][e]
[s]Ah...[n]Uu...[n][w][e]

[msg MSG_KAGE_01_03 [Male Student]]
[s]Uhh...[n]Ah...[n][w][e]
[s]......[n][w][e]
[s]Ahh...[n][w][e]

[msg MSG_KAGE_01_04 [Male Student]]
[s]Uhaaa...[n]Auuu...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_01_05 [Male Student]]
[s]Uhh...[n]Uhwa...[n]Aah...[n][w][e]
[s]Ahhh...[n][w][e]

[msg MSG_KAGE_01_06 [Male Student]]
[s]Ahhh...[n][w][e]
[s]Uu...[n]Uhh...[n][w][e]

[msg MSG_KAGE_01_07 [Male Student]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]Uaaaah...[n][w][e]

[msg MSG_KAGE_01_08 [Male Student]]
[s]......[n][w][e]
[s]Uh...[n]Uhhhh...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_01_09 [Male Student]]
[s]Uh...[n]Uh...[n][w][e]
[s]Uhhhhhh...[n]Uh...[n][w][e]

[msg MSG_KAGE_01_10 [Male Student]]
[s]Uaaah...[n]Ahh...[n][w][e]
[s]......[n]Uhhh...[n][w][e]

[msg MSG_KAGE_02_01 [Female Student]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_02_02 [Female Student]]
[s]......[n][w][e]
[s]Ah...[n]Uu...[n][w][e]

[msg MSG_KAGE_02_03 [Female Student]]
[s]Uhh...[n]Ah...[n][w][e]
[s]......[n][w][e]
[s]Ahh...[n][w][e]

[msg MSG_KAGE_02_04 [Female Student]]
[s]Uhaaa...[n]Auuu...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_02_05 [Female Student]]
[s]Uhh...[n]Uhwa...[n]Aah...[n][w][e]
[s]Ah...[n][w][e]

[msg MSG_KAGE_02_06 [Female Student]]
[s]Ahhh...[n][w][e]
[s]Uu...[n]Uhh...[n][w][e]

[msg MSG_KAGE_02_07 [Female Student]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]Uaaaah...[n][w][e]

[msg MSG_KAGE_02_08 [Female Student]]
[s]......[n][w][e]
[s]Uh...[n]Uhhhh...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_02_09 [Female Student]]
[s]Uh...[n]Uhhhh...[n][w][e]
[s]Uhhhhhh...[n]Uh...[n][w][e]

[msg MSG_KAGE_02_10 [Female Student]]
[s]Uaaah...[n]Ahh...[n][w][e]
[s]......[n]Uhhh...[n][w][e]

[msg MSG_KAGE_03_01 [Man]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_03_02 [Man]]
[s]......[n][w][e]
[s]Ah...[n]Uu...[n][w][e]

[msg MSG_KAGE_03_03 [Man]]
[s]Uhh...[n]Ah...[n][w][e]
[s]......[n][w][e]
[s]Ahh...[n][w][e]

[msg MSG_KAGE_03_04 [Man]]
[s]Uhaaa...[n]Auuu...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_03_05 [Man]]
[s]Uhh...[n]Uhwa...[n]Aah...[n][w][e]
[s]Ah...[n][w][e]

[msg MSG_KAGE_03_06 [Man]]
[s]Ahhh...[n][w][e]
[s]Uu...[n]Uhh...[n][w][e]

[msg MSG_KAGE_03_07 [Man]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]Uaaaah...[n][w][e]

[msg MSG_KAGE_03_08 [Man]]
[s]......[n][w][e]
[s]Uh...[n]Uhhhh...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_03_09 [Man]]
[s]Uh...[n]Uhh...[n][w][e]
[s]Uhhhhhh...[n]Uh...[n][w][e]

[msg MSG_KAGE_03_10 [Man]]
[s]Uaaah...[n]Ahh...[n][w][e]
[s]......[n]Uhhh...[n][w][e]

[msg MSG_KAGE_04_01 [Woman]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_04_02 [Woman]]
[s]......[n][w][e]
[s]Ah...[n]Uu...[n][w][e]

[msg MSG_KAGE_04_03 [Woman]]
[s]Uhh...[n]Ah...[n][w][e]
[s]......[n][w][e]
[s]Ahh...[n][w][e]

[msg MSG_KAGE_04_04 [Woman]]
[s]Uhaaa...[n]Auuu...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_04_05 [Woman]]
[s]Uhh...[n]Uhwa...[n]Aah...[n][w][e]
[s]Ah...[n][w][e]

[msg MSG_KAGE_04_06 [Woman]]
[s]Ahhh...[n][w][e]
[s]Uu...[n]Uhh...[n][w][e]

[msg MSG_KAGE_04_07 [Woman]]
[s]......[n][w][e]
[s]......[n][w][e]
[s]Uaaaah...[n][w][e]

[msg MSG_KAGE_04_08 [Woman]]
[s]......[n][w][e]
[s]Uh...[n]Uhhhh...[n][w][e]
[s]......[n][w][e]

[msg MSG_KAGE_04_09 [Woman]]
[s]Uh...[n]Uhh...[n][w][e]
[s]Uhhhhhh...[n]Uh...[n][w][e]

[msg MSG_KAGE_04_10 [Woman]]
[s]Uaaah...[n]Ahh...[n][w][e]
[s]......[n]Uhhh...[n][w][e]

[msg MSG_KAGE_FIRST]
[s]> It's one of The Lost--a victim of[n]the Apathy Syndrome that's causing[n]such a stir.[n][w][e]
[s]> You cannot get a meaningful[n]response out of this person.[n][w][e]

[msg MSG_IRAI_MUKIRYOKU_FIRST [Female Student]]
[s]Ci...elo... Mist...[n][w][e]

[msg MSG_IRAI_MUKIRYOKU_NOHAV [Female Student]]
[s]Want... Ci...elo... Mist......[n][w][e]
[s]> She seems to want something...[n][f 1 4][e]

[msg MSG_IRAI_MUKIRYOKU_WANT]
[s]> She's pointing to your[n][f 4 4 3 0 1396].[n][w][e]
[s]> Give her the [f 4 4 3 0 1396]?[n][w][e]

[sel MSG_IRAI_MUKIRYOKU_WANT_ top]
[s]Yes[e]
[s]No[e]

[msg MSG_IRAI_MUKIRYOKU_THX [Female Student]]
[s]Thank... you...[n][w][e]
[s]> The girl downed one [f 4 4 3 0 1396][n]after another![n][f 1 4][e]
[s]> She drank 20 cans in all![n][f 1 4][e]
[s]Ahh... that hit the spot.[n][w][e]
[s]> The student looks healthier now.[n][f 1 4][e]
[s]Huh...? A missing persons flyer...?[n][w][e]
[s]Oh, I guess I haven't been back home[n]in a while...[n][w][e]
[s]I'll give my parents a call later.[n]Thanks![n][w][e]
[s]> The girl decided to phone home.[n][f 1 4][e]
[s]> You succeeded in delivering cool[n]liquid refreshment.[n][f 1 4][e]

[msg MSG_IRAI_MUKIRYOKU_NOTEN [Female Student]]
[s]Not... Enough...[n][w][e]
[s]> You don't have enough[n][f 4 4 3 0 1396]. The girl gave the[n][f 4 4 3 0 1396] back to you.[n][f 1 4][e]

[msg MSG_IRAI_MUKIRYOKU_END [Female Student]]
[s]Thanks... I feel better now...[n][w][e]

