
[msg WOULDYOULIKETO]
[s]> Would you like to equip the [f 2 4 0] on[n]that party member?[n][w][e]

[msg WOULDYOULIKETOY]
[s]This seems like an upgrade for Yukari....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Yukari?[n][w][e]

[msg WOULDYOULIKETOA]
[s]This seems like an upgrade for Aigis....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Aigis?[n][w][e]

[msg WOULDYOULIKETOM]
[s]This seems like an upgrade for Mitsuru....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Mitsuru?[n][w][e]

[msg WOULDYOULIKETOJ]
[s]This seems like an upgrade for Junpei....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Junpei?[n][w][e]

[msg WOULDYOULIKETOF]
[s]This seems like an upgrade for Fuuka....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Fuuka?[n][w][e]

[msg WOULDYOULIKETOAK]
[s]This seems like an upgrade for Akihiko....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Akihiko?[n][w][e]

[msg WOULDYOULIKETOK]
[s]This seems like an upgrade for Ken....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Ken?[n][w][e]

[msg WOULDYOULIKETOS]
[s]This seems like an upgrade for Shinjiro....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Shinjiro?[n][w][e]

[msg WOULDYOULIKETOKO]
[s]This seems like an upgrade for Koromaru....[n][w][e]
[s]> Would you like to equip the [f 2 4 0][n]on Koromaru?[n][w][e]

[msg UPGRADE_YUKARI [Yukari]]
[s][bup 2 202 0 0]Thanks, I'll take good care of it![n][w][e]

[msg UPGRADE_AIGIS [Aigis]]
[s][bup 3 202 0 0]Equipment upgrade confirmed. I anticipate an[n]improved combat performance.[n][w][e]

[msg UPGRADE_MITSURU [Mitsuru]]
[s][bup 4 202 0 0]You have my gratitude. I won't let[n]you down.[n][w][e]

[msg UPGRADE_JUNPEI [Junpei]]
[s][bup 5 202 0 0]Aw yeah, upgrade time, baby![n]Let's keep it rollin'![n][w][e]

[msg UPGRADE_FUUKA [Fuuka]]
[s][n][w][e]

[msg UPGRADE_AKIHIKO [Akihiko]]
[s][bup 7 202 0 0]There's no substitute for training, but I'll take solid gear[n]where we can find it too.[n][w][e]

[msg UPGRADE_KEN [Ken]]
[s][bup 8 202 0 0]Thank you very much.[n]I'll do my best to be of help![n][w][e]

[msg UPGRADE_SHINJI [Shinjiro]]
[s][bup 9 202 0 0]Good choice. I'll see[n]to it that you don't regret it.[n][w][e]

[msg UPGRADE_KOROMARU [Koromaru]]
[s][bup 10 202 0 0]Woof![n][w][e]
[s]> Koromaru is excited about the new equipment.[n][f 1 4][e]

[sel YEAHMANIWANNADOIT top]
[s]Equip [f 2 4 0][e]
[s]Keep current equipment[e]