
[sel SEL_019 top]
[s]Akihiko[e]
[s]Shinjiro[e]
[s]Ken[e]
[s]Junpei[e]
[s]I don't know...[e]

[msg MSG_020]
[s][f 3 1 1 0 0 0]> It's Junpei's voice....[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 0]> He's losing his breath[n]and rushing toward you.....[n][f 1 3 65535][w][e]

[msg MSG_021 [Junpei]]
[s][bup 5 1 3 0][f 3 1 1 0 0 65]*wheeze* *wheeze* *wheeze*[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 0][f 4 2]…[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 66]It's impossible. I....[n]I just thought of you as a girlfriend.....[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 67]But it's not as simple as that.[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 68]You're really important.[n]Really, really important....[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 69]Important, important....[n][f 1 3 65535][w][e]

[msg MSG_022]
[s][f 3 1 1 0 0 0]> Junpei holds you tightly.[n][f 1 3 65535][w][e]

[msg MSG_023 [Junpei]]
[s][bup 5 1 3 0][f 3 1 1 0 0 70]I am glad....[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 71]you are here....[n][f 1 3 65535][w][e]

[msg MSG_024]
[s][f 3 1 1 0 0 0]> The sounds of footsteps and[n]familiar voices are getting closer.[n][f 1 3 65535][w][e]

[msg MSG_025 [Junpei]]
[s][bup 5 1 3 0][f 3 1 1 0 0 72]Haha... Can't they take a hint....[n][f 1 3 65535][w][e]

[msg MSG_026]
[s][f 3 1 1 0 0 0]> Under the gentle sunlight,[n]in the warm arms of Junpei....[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 0]> You're getting sleepier...[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 0]> Your eyelids feel heavy...[n][f 1 3 65535][w][e]

[sel SEL_027 top]
[s]Close your eyes[e]
[s]......[e]


[msg MSG_029 [Akihiko]]
[s][bup 7 3 3 0][f 3 1 1 0 0 73]*gasp* *gasp* *cough*[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 74][f 4 2]... Are you all right!?[n][f 1 3 65535][w][e]
[s][bup 7 2 3 0][f 3 1 1 0 0 75]*sigh* Thank god...[n][f 1 3 65535][w][e]
[s][f 3 1 1 0 0 76]I couldn't find you, and... I thought[n]you might've gone off somewhere...[n][f 1 3 65535][w][e]


[msg MSG_076 [Junpei]]
[s][f 3 1 1 0 0 0]I'll always be by your side...[n][f 1 2 150][w][e]

