[msg TRY_AGAIN]
[s]> Would you like to try again?[n][w][e]

[sel PLAYWAY top]
[s]Play until I win[e]
[s]Play once[e]
[s]Go back[e]

[msg ColorTest]
[s]Colors: [clr 0]0 [clr 1]1 [clr 2]2 [clr 3]3 [clr 4]4 [clr 5]5 [clr 6]6 [clr 7]7 [clr 8]8 [clr 9]9[clr 10]10 [clr 11]11 [clr 12]12 [clr 13]13 [clr 14]14 [clr 15]15[n]
[clr 16]16 [clr 17]17 [clr 18]18 [clr 19]19 [clr 20]20 [clr 21]21 [clr 22]22 [clr 23]23 [clr 24]24 [clr 25]25 [clr 26]26 [clr 27]27 [clr 28]28 [clr 29]29 [clr 30]30 [clr 31]31[w][e]

[msg GO_BACK_HOME]
[s]> Today's the Promised Day...[n]I should head to Tartarus...[n][w][e]

[msg UFO_CATHER_01]
[s]> It's a crane game.[n][w][e]
[s]> One of the prizes is a [clr 3][f 2 4 0][clr 0].[n][w][e]
[s]> It costs 200 yen to play. How will[n]you play?[n]           (Money: [clr 1][f 2 4 1] yen[clr 0])[n][w][e]

[msg UFO_CATHER]
[s]> It's a crane game.[n][w][e]
[s]> One of the prizes is a [clr 3][f 2 4 0][clr 0].[n][w][e]
[s]> It costs 200 yen to play. How will[n]you play?[n]           (Money: [clr 1][f 2 4 1] yen[clr 0])[n][w][e]

[msg UFO_CATHER_GET_WHO]
[s]> You won![n][w][e]
[s]> Obtained [clr 3][f 2 4 1][clr 0]![n][w][e]

[msg UFO_CATHER_GET_WHEN]
[s]> You won![n][w][e]
[s]> Obtained [clr 3][f 2 4 1][clr 0]![n][w][e]

