[sel MISSING_PERSON_SELL top]
[f 0 5 65278][f 2 1]Send a party member[e]
[f 0 5 65278][f 2 1]Go together[e]
[f 0 5 65278][f 2 1]No[e]

[msg RETURN_TO_YUKARI [Yukari]]
[s][bup 2 201 0 0]I'm on my way. Give me a second.[n][w][e]

[msg RETURN_TO_YUKARI_2 [Yukari]]
[s][bup 2 201 0 0]Sorry to keep you waiting, leave the[n]rest to me.[n][w][e]

[msg RETURN_TO_AIGIS [Aigis]]
[s][bup 3 201 0 0]Please wait there, I'll arrive[n]shortly.[n][w][e]

[msg RETURN_TO_AIGIS_2 [Aigis]]
[s][bup 3 201 0 0]I appreciate your patience.[n]Beginning escort.[n][w][e]

[msg RETURN_TO_MITSURU [Mitsuru]]
[s][bup 4 201 0 0]I'll go, then. Just hold on for[n]a little longer.[n][w][e]

[msg RETURN_TO_MITSURU_2 [Mitsuru]]
[s][bup 4 201 0 0]My apologies for the delay. I'll[n]make sure they get back safely.[n][w][e]

[msg RETURN_TO_JUNPEI [Junpei]]
[s][bup 5 201 0 0]There's my cue! Hang tight!.[n][w][e]

[msg RETURN_TO_JUNPEI_2 [Junpei]]
[s][bup 5 201 0 0]Alright, I'm here! I'll handle this.[n][w][e]

[msg RETURN_TO_AKIHIKO [Akihiko]]
[s][bup 7 201 0 0]I'm heading over now, I'll be there soon.[n][w][e]

[msg RETURN_TO_AKIHIKO_2 [Akihiko]]
[s][bup 7 201 0 0]Sorry for the wait, leave this to me. I'll[n]keep them safe.[n][w][e]

[msg RETURN_TO_KEN [Ken]]
[s][bup 8 201 0 0]You'd like me to go? Don't worry I'll[n]be there in a jiffy.[n][w][e]

[msg RETURN_TO_KEN_2 [Ken]]
[s][bup 8 201 0 0]Sorry for making you wait, I'll make[n]sure this person gets back safely.[n][w][e]

[msg RETURN_TO_KOROMARU [Koromaru]]
[s][bup 10 201 0 0]Woof![n][w][e]
[s]> Koromaru begins escorting the person[n]out of Tartarus.[n][f 1 4][e]

[msg RETURN_TO_SHINJI [Shinjiro]]
[s][bup 9 201 0 0]Just hang on, I'll be quick....[n][w][e]

[msg RETURN_TO_SHINJI_2 [Shinjiro]]
[s][bup 9 201 0 0]Yo, sorry 'bout the wait. I'll handle[n]this from here.[n][w][e]





