[sel ORDER_SEL top]
[s]Regroup[e]
[s]Split up[e]
[s]Priority: explore[e]
[s]Priority: defeat Shadows[e]
[s]Request a specific BGM[e]
[s]Ask Fuuka for something[e]
[s]Change party[e]
[s]Cancel[e]
[s]Debug[e]

[sel HUKA_OREDER_SEL top]
[s]Ask for an Escape Route[e]
[s]Ask for a specific BGM[e]
[s]Change party[e]
[s]Cancel the request[e]
[s]Debug[e]

[msg REMOVE_OR_ADD]
[s][f 0 4 255]> Would you like to remove or add party members?[w][e]

[sel REMOVE_OR_ADD_SEL top]
[s]Add[e]
[s]Remove[e]
[s]Finish[e]

[msg WHO_TO_ADD]
[s][f 0 4 255]> Who would you like to add to your party?[w][e]

[msg FULL_PARTY]
[s][f 0 4 255]> Your party is full! You cannot add[n]any more party members.[w][e]

[msg NOBODY_AVAIL]
[s][f 0 4 255]> There are no available party members left![w][e]

[msg REMOVE_YESNO]
[s][f 0 4 255]> Would you like to remove party members?[w][e]

[msg REMOVE]
[s][f 0 4 255]> Who would you like to remove from your party?[w][e]

[msg EMPTY_PARTY]
[s][f 0 4 255]> Your party is empty! You cannot remove[n]any more party members.[w][e]

[sel PARTY_MEMBERS top]
[s]Yukari[e]
[s]Aigis[e]
[s]Mitsuru[e]
[s]Junpei[e]
[s]Akihiko[e]
[s]Ken[e]
[s]Shinjiro[e]
[s]Koromaru[e]
[s]Cancel[e]

[msg REFRESH_FLOOR_NOTIF [NOTICE]]
[s]> The next floor will be loaded. This is to[n]force the party to be refreshed.[w][e]
[s]> TODO: find a method to refresh[n]the floor properly.[w][e]
