[sel FORTUNE_TELLER_TANAKA top]
[s]Watch the fortune teller program[e]
[s]Turn off the tv[e]

[msg FUZZY_PIC]
[s]> The picture appears fuzzy....[n][w][e]
[s]> What should you do?[n][w][e]

[sel MORE_OR_LESS top]
[s]Adjust the knob for more detail[e]
[s]Leave it as is[e]



[msg ORB_PONDER [Mysterious Figure]]
[s]Welcome visitor...[n][w][e]
[s]I sense you are in need[n]of information.... [n][w][e]
[s]Information I can provide for you..... [n][w][e]
[s]Give me some time to ponder my orb...[n][w][e]
[s]Yes! I see it clearly now![n][w][e]



[msg TVTIME_CHOICE]
[s]> What's on TV tonight?[n][w][e]

[msg ACADEMICS_LVL_IS [Mysterious Figure]]
[s]In the celestial tapestry of academia, you hover just[n][f 2 4 0] points away from the zenith of scholarly attainment.[n][w][e]

[msg ACADEMICS_LVL_IS [Mysterious Figure]]
[s]In the celestial tapestry of academia, you hover just[n][f 2 4 0] points away from the zenith of scholarly attainment.[n][w][e]

[msg ACADEMICS_MAXU [Mysterious Figure]]
[s]In the celestial symphony of[n]knowledge, I discern a brilliant constellation of[n]maximum academics illuminating your path.[n][w][e]

[msg CHARM_LVL_IS [Mysterious Figure]]
[s]In the ethereal realm of charm, you stand on the brink[n]of enchantment, mere [f 2 4 0] points away from ascending[n]to the pinnacle of charisma, guided by the whims of fate.[n][w][e]

[msg CHARM_MAXU [Mysterious Figure]]
[s]In the cosmic dance of destiny,[n]your essence shines with maximum charm,[n]a radiant beacon amidst the ebb and flow of time.[n][w][e]

[msg COURAGE_LVL_IS [Mysterious Figure]]
[s]In the cosmic tapestry of courage, you teeter[n]on the edge of bravery, just [f 2 4 0] points away[n]from reaching the highest echelons of valor.[n][w][e]

[msg COURAGE_MAXU [Mysterious Figure]]
[s]In the tapestry of fate, I[n]perceive a blazing ember of maximum courage ablaze[n]within your soul, like a phoenix rising from the ashes.[n][w][e]

[msg ORB_PONDER_2 [Mysterious Figure]]
[s]I hope this information helps....[n][w][e]
[s]Until next time.... [n][w][e]
[s]Goodbye.... [n][w][e]

[msg ORB_PONDER_2_CAT [Meowsterious Figure]]
[s][bup 67 161 0 3]I hope this information helps....[n][w][e]
[s][bup 67 161 0 3]Until next time.... [n][w][e]
[s][bup 67 161 0 3]Goodbye.... [n][w][e]

[msg WTFWASTHAT]
[s]> Was that a cat???[n][w][e]

[msg FORTUNE_ACADEMICS_PROGRESS_1 [Mysterious Figure]]
[s]In the realm of academia, the path[n]stretches ahead, still in its infancy,[n]you have much ground left to cover.[n][w][e]

[msg FORTUNE_ACADEMICS_PROGRESS_2 [Mysterious Figure]]
[s]With academia within reach, the[n]journey feels halfway traversed, yet still[n]with ample terrain to explore.[n][w][e]

[msg FORTUNE_ACADEMICS_PROGRESS_3 [Mysterious Figure]]
[s]As academia nears completion, the[n]destination glimmers on the horizon,[n]though challenges persist.[n][w][e]

[msg FORTUNE_ACADEMICS_PROGRESS_4 [Mysterious Figure]]
[s]With academia nearly mastered, the[n]final hurdles stand tall, awaiting[n]your triumphant ascent.[n][w][e]

[msg FORTUNE_CHARM_PROGRESS_1 [Mysterious Figure]]
[s]Within the realm of charm, the path[n]stretches ahead, its beginnings faint, with a[n]wealth of allure awaiting cultivation.[n][w][e]

[msg FORTUNE_CHARM_PROGRESS_2 [Mysterious Figure]]
[s]With charm within grasp, the journey feels[n]halfway traveled, yet with a myriad of truth to uncover.[n][w][e]

[msg FORTUNE_CHARM_PROGRESS_3 [Mysterious Figure]]
[s]As charm nears its apex, the[n]enchanting aura beckons, though mysteries[n]linger beneath its surface.[n][w][e]

[msg FORTUNE_CHARM_PROGRESS_4 [Mysterious Figure]]
[s]With charm on the verge of[n]mastery, the final nuances stand poised,[n]awaiting your captivating ascent.[n][w][e]

[msg FORTUNE_COURAGE_PROGRESS_1 [Mysterious Figure]]
[s]Amidst the realm of courage, the road[n]unfurls before you, its journey in its earliest[n]stages, with boundless bravery awaiting discovery...[n][w][e]

[msg FORTUNE_COURAGE_PROGRESS_2 [Mysterious Figure]]
[s]With courage beckoning, the voyage[n]feels halfway completed, yet with vast[n]reservoirs of valor yet to be tapped.[n][w][e]

[msg FORTUNE_COURAGE_PROGRESS_3 [Mysterious Figure]]
[s]As courage approaches its summit, the[n]allure of fearlessness calls out, though[n]obstacles linger on the path.[n][w][e]

[msg FORTUNE_COURAGE_PROGRESS_4 [Mysterious Figure]]
[s]With courage on the brink of mastery,[n]the ultimate tests stand resilient,[n]anticipating your bold ascent..[n][w][e]
