[msg MSG_TARTAROS_BTL_YUKARI_ [Yukari Takeba]]
[s][bup 2 201 0 0]If you're not gonna move, then we'll make you![n][w][e]

[msg MSG_TARTAROS_BTL_YUKARI__2 [Yukari Takeba]]
[s][bup 2 201 0 0]Ready? Let's go![n][w][e]

[msg MSG_TARTAROS_BTL_JUNPEI_ [Junpei Iori]]
[s][bup 5 201 0 0]Move out, squad! Keep your eyes on me![n][w][e]

[msg MSG_TARTAROS_BTL_JUNPEI__2 [Junpei Iori]]
[s][bup 5 201 0 0]Looks tougher than I thought... But ain't nothin'[n]stoppin' me![n][w][e]

[msg MSG_TARTAROS_BTL_SANADA_ [Akihiko Sanada]]
[s][bup 7 201 0 0]Sorry, but we're breaking through![n][w][e]

[msg MSG_TARTAROS_BTL_SANADA__2 [Akihiko Sanada]]
[s][bup 7 201 0 0]This'll be fun. C'mon, let's move![n][w][e]

[msg MSG_TARTAROS_BTL_MITSURU [Mitsuru Kirijo]]
[s][bup 4 201 0 0]Incoming! Brace yourselves![n][w][e]

[msg MSG_TARTAROS_BTL_MITSURU_2 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]Let's get through this![n][w][e]

[msg MSG_TARTAROS_BTL_MITSURU_3 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]I'll leave this to you![n][w][e]

[msg MSG_TARTAR_BTL_PT_MITSUR [Mitsuru Kirijo]]
[s]Stay alert! The enemy's powers are unknown![n][w][e]

[msg MSG_TARTAR_BTL_PT_MITSUR_2 [Mitsuru Kirijo]]
[s]Are you ready? We're forcing our way through![n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_0 [Aigis]]
[s][bup 3 201 0 0]Approaching enemy Shadow. Eliminating target.[n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_1 [Aigis]]
[s][bup 3 201 0 0]Entering combat. Come and get it, as they say.[n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_2 [Aigis]]
[s][bup 3 201 0 0]This may be a tough battle. Let's exercise caution![n][w][e]

[msg MSG_TARTAROS_BTL_AEGIS_3 [Aigis]]
[s][bup 3 201 0 0]I'll give it everything I've got, so let's work[n]together![n][w][e]

[msg MSG_TARTAROS_BTL_KOROMAR [Koromaru]]
[s][bup 10 201 0 0]Grrr... Arf![n][w][e]

[msg MSG_TARTAROS_BTL_KOROMAR_2 [Koromaru]]
[s][bup 10 201 0 0]Grrrrrr...![n][w][e]

[msg MSG_TARTAROS_BTL_AMADA_0 [Ken Amada]]
[s][bup 8 201 0 0]Come on, bring it! I'll take you on![n][w][e]

[msg MSG_TARTAROS_BTL_AMADA_1 [Ken Amada]]
[s][bup 8 201 0 0]Here it comes! Let's take it down![n][w][e]

[msg MSG_TARTAROS_BTL_ARAGAKI [Shinjiro Aragaki]]
[s][bup 9 201 0 0]Get ready, here it comes![n][w][e]

[msg MSG_TARTAROS_BTL_ARAGAKI_2 [Shinjiro Aragaki]]
[s][bup 9 201 0 0]If we can't get through, then we're just gonna[n]have to pulverize 'em.[n][w][e]

[msg MSG_TARTAROS_BTL_FUKA_1 [Fuuka Yamagishi]]
[s]Incoming enemy Shadow![n][w][e]

[msg MSG_TARTAROS_BTL_FUKA_2 [Fuuka Yamagishi]]
[s]I'll support you! We'll get through this together![n][w][e]

[msg MSG_TARTAROS_BTL_FUKA_3 [Fuuka Yamagishi]]
[s]You can do this! I believe in you![n][w][e]


[msg var6CHECK]
[s]var 6 is [f 2 4 1][n]var5 is [f 2 4 0][n]var4 is [f 2 4 2] .[w][e]

[msg MSG_000_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 3 1 3 0 65535 4086 0 0]Well done, everyone. That was a formidable opponent.[n][w][e]

[msg MSG_001_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]Heh, okay, my stunning performance aside, aren't all of us totally on the same wavelength now?[n][w][e]

[msg MSG_002_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]Let's not bring up your "stunning performance" ever... And I'd rather not be on the same wavelength as you, either.[n][w][e]

[msg MSG_003_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]Wha— Why not!? Teamwork makes the dream work, right?[n][w][e]

[msg MSG_004_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1123 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 3 0 25 25]Well, I guess you have a point... Let's keep up the good work, [uf 4 1]-kun.[n][w][e]

[msg MSG_005_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 4 23 1 3 0 25 25]We're doing good work for a new team. Let's keep up the pace.[n][w][e]
[s][bup 4 201 0 0]Right now, Tartarus is our only lead to unravel the mystery behind the Dark Hour.[n][w][e]

[msg MSG_006_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]Alrighty! Then let's just keep on moving![n][w][e]

[msg MSG_007_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1114 0 0]We can move on now, but the next floor doesn't look any different...[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 3 25 25]You don't think it'll be the same old thing forever, do you...?[n][w][e]

[sel SEL_008_0_00 top]
[s]Only one way to find out.[e]
[s]Maybe it will be.[e]
[s]I can't say for sure.[e]

[msg MSG_009_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1119 0 0]Yeah, you're right. It's just... I want to at least feel like we're making progress.[n][w][e]

[msg MSG_010_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2062 0 0]I getcha, Yuka-tan. Spend too long in the Tartarus tartar sauce, and anybody'd be cravin' for barbecue.[n][w][e]

[msg MSG_010_5_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]What the heck are you saying...? Well, at least you agree it's hard to push through the same thing over and over again.[n][w][e]

[msg MSG_011_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 3 1 3 0 65535 4025 0 0][uf 4 23 1 2 0 25 25]Right. Part of our objective is to discover what lies ahead. All we can do now is keep moving forward.[n][w][e]

[msg MSG_012_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]No point overthinking things now... All we gotta do is keep moving forward.[n][w][e]
[s][uf 4 5 2 2 65535 65535 0 0][uf 4 23 1 2 2 25 25]...After all, I've already made up my mind.[n][w][e]

[msg MSG_013_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2105 0 0][uf 4 23 1 3 1 25 25]Oh, look at you all fired up. What's gotten into you all of a sudden?[n][w][e]

[msg MSG_014_0_00 [Yukari Takeba]]
[s][uf 4 5 2 4 65535 65535 0 0][uf 4 23 1 2 4 25 25]Oh, um... Nothing, really. Anyway, enough about me.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]We gotta keep going, right? C'mon, let's get a move on.[n][w][e]

[msg MSG_015_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2095 0 0][uf 4 23 1 3 1 25 25]And another one bites the dust! We're on a roll, guys![n][w][e]
[s][bup 5 201 0 0]While we're at it, how about we spice things up every now and then? Like by changin' up the leader...?[n][w][e]

[msg MSG_016_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 3 25 25]What? And here I was, worried about what you'd say next...[n][w][e]

[msg MSG_016_5_0 [Junpei Iori]]
[s][bup 5 201 0 0]Don'tcha wanna see how I'd run this whole shebang? Well, don'tcha?[n][w][e]

[sel SEL_017_0_00 top]
[s]Let's do it.[e]
[s]Should we switch?[e]
[s]I'm fine with whatever.[e]

[msg MSG_018_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 3 1 3 0 65535 4122 0 0][uf 4 23 1 3 0 25 25]...Wait. It wouldn't be wise for a change in command in the middle of an expedition.[n][w][e]
[s][bup 4 201 0 0]We're making steady progress under [uf 4 1]'s lead, so let's continue as we have been.[n][w][e]

[msg MSG_019_0_00 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 3 3 25 25]Fiiine, sure. I guess.[n][w][e]
[s][uf 4 5 3 3 65535 65535 0 0]But I'm pretty sure I could just take down the enemies here aaaaaall by myself...[n][w][e]

[msg MSG_020_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1076 0 0][uf 4 23 1 2 6 25 25]Chill out, Junpei... If you're not careful, it won't be long till you get hurt.[n][w][e]

[msg MSG_021_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 4 23 1 2 0 25 25]Takeba's right. We can expect another strong enemy to appear.[n][w][e]
[s][bup 4 201 0 0]Don't let your guard down as we proceed.[n][w][e]

[msg MSG_021_1_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0]Okaaay, whatever... Guess there's always next time.[n][w][e]

[msg MSG_022_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1113 0 0]Phew... We won. Seems like we'll keep running into stronger enemies whenever we enter a new area.[n][w][e]

[msg MSG_023_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]Akihiko will also be back soon. We could always pick things up once he's ready to join us.[n][w][e]

[msg MSG_024_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]I can't wait for Sanada-san to hop on board.[n][w][e]
[s][bup 5 201 0 0]Then we'll finally be a four-man band! You know, the standard for an RPG.[n][w][e]
[s][uf 4 5 3 2 65535 65535 0 0]Junpei Quest: The Legend of Junpei, Tower of Mystery! Now, let us head off, comrades![n][w][e]

[msg MSG_025_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1143 0 0][uf 4 23 1 2 6 25 25]We don't need you to head off anywhere. Haven't you learned your lesson at all?[n][w][e]
[s][bup 2 201 0 0]We need your head screwed on.[n][w][e]

[msg MSG_026_0_00 [Junpei Iori]]
[s][uf 4 5 3 2 65535 65535 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 3 2 25 25]Whaddaya mean? I've got a perfectly good head on my shoulders![n][w][e]

[msg MSG_026_5_0 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 3 1 3 0 65535 4106 0 0][uf 4 23 1 3 0 25 25]In that case, I suppose there's no need to worry about your studies?[n][w][e]

[msg MSG_027_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]Er, well, about that... Haha...[n][w][e]
[s][uf 4 5 3 2 65535 65535 0 0][uf 4 23 1 3 2 25 25]Oh, Brave Knight [uf 4 2]! Let us hurry and depart![n][w][e]

[msg MSG_028_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 3 1 3 0 65535 4107 0 0]You did an excellent job, especially against such a strong enemy.[n][w][e]
[s][bup 4 201 0 0]The same can be said about the battle with the large Shadow. I'm surprised at how fast you've all improved.[n][w][e]

[msg MSG_029_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2095 0 0][uf 4 23 1 3 1 25 25]It's definitely all natural-born talent! I think I'll make it all the way to the top at this rate![n][w][e]

[msg MSG_030_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25][uf 4 23 1 3 0 25 25]You always get so carried away... But if you're aiming for the top, I guess I'll tag along for the ride.[n][w][e]

[msg MSG_031_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]Heh, I see you're all as dependable as ever.[n][w][e]
[s][bup 4 201 0 0]There may not be a need for Akihiko or me to join your battles... Though Akihiko wouldn't be very happy about that.[n][w][e]

[msg MSG_032_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2133 0 0]Haha, I'd pay to see Sanada-san pouting. It'd be hilarious.[n][w][e]

[msg MSG_032_3_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]That's rich, coming from you.[n][w][e]

[msg MSG_032_5_0 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 3 0 25 25]What awaits us is an unknown frontier. All of you, proceed with caution.[n][w][e]

[msg MSG_033_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1119 0 0][uf 4 23 1 2 3 25 25]*sigh* What's with these back-to-back fights?[n][w][e]

[msg MSG_034_0_00 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 3 3 25 25]Yeah, this is a first. It's like, pacing, anyone?[n][w][e]

[msg MSG_035_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 3 0 25 25]I can't get a read on a pattern for these floors... There's simply too much about which we're still in the dark.[n][w][e]
[s][bup 4 201 0 0]We need to prepare even more thoroughly, and retreat promptly when we're depleted.[n][w][e]

[msg MSG_036_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1061 0 0]Maybe we'd have an easier time with Sanada-senpai around.[n][w][e]

[msg MSG_037_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]Yeah... Wouldn't he be happy about fightin' a bunch of tough enemies anyways?[n][w][e]

[msg MSG_038_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]I can definitely see that... Nevertheless, he'd greatly increase our firepower.[n][w][e]
[s][bup 4 201 0 0][uf 4 23 1 3 0 25 25]Well, if you plan on proceeding, then do so carefully. I'm counting on you.[n][w][e]

[msg MSG_039_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 3 1 3 0 65535 4115 0 0]Nicely done. Doesn't seem like you're having any problems.[n][w][e]
[s][bup 4 201 0 0]Though I've never underestimated you in the first place, you're performing better than expected.[n][w][e]

[sel SEL_040_0_00 top]
[s]We're in top form.[e]
[s]We're not that great.[e]
[s]You're making me blush.[e]

[msg MSG_041_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2095 0 0][uf 4 23 1 3 1 25 25]Heheh! Now I'm gettin' pumped up! Ain't every day you get a compliment from Kirijo-senpai.[n][w][e]

[msg MSG_042_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 4 23 1 3 0 25 25]You— ...r— ...lly doin— ...well. I hav— ...hope— ...for you.[n][w][e]

[msg MSG_043_0_00 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2138 0 0][uf 4 23 1 3 3 25 25]...Huh? Come again?[n][w][e]

[msg MSG_044_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]You heard what she said... Stop fishing for more.[n][w][e]

[msg MSG_045_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]N-No! I seriously couldn't hear her! There was, like, static or something.[n][w][e]

[msg MSG_046_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 3 0 25 25]Static...?[n][w][e]
[s][bup 4 201 0 0]...Check, check, one, two, one, two. How is it? Can you hear me?[n][w][e]

[msg MSG_047_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1151 0 0]Yeah, just fine.[n][w][e]

[msg MSG_048_0_00 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 3 4 25 25]Wha...? Was it just my imagination? Sorry, my bad.[n][w][e]

[msg MSG_049_0_00 [Mitsuru Kirijo]]
[s][bup 4 201 0 0]No, if you have any concerns, don't be afraid to relay them to me.[n][w][e]
[s][bup 4 201 0 0][uf 4 23 1 3 0 25 25]For the time being, it seems there aren't any problems, so let's get back to exploring.[n][w][e]

[msg MSG_050_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4112 0 0]I can't let my guard down... Especially not around those Gatekeepers.[n][w][e]

[msg MSG_051_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0]...I've never seen you with your guard down, though—not even in the dorm.[n][w][e]
[s][bup 2 201 0 0]When we're up late on a mission, I've never even seen you yawn, much less doze off.[n][w][e]
[s][bup 2 201 0 0]Then the next day, you're all dressed up and drinking black tea before heading to school fifteen minutes later.[n][w][e]

[sel SEL_052_0_00 top]
[s]You're sure observant.[e]
[s]I should follow her lead.[e]
[s]Seems exhausting.[e]

[msg MSG_053_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1064 0 0][uf 4 23 1 2 3 25 25]Huh? Uh, no, not really. When you live in the same dorm, you start to pick some things up.[n][w][e]

[msg MSG_054_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4031 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 5 1 25 25]Once it becomes a habit, it's all second nature.[n][w][e]

[msg MSG_055_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 4 23 1 5 0 25 25]Besides... wouldn't you find it offensive if I were to take it easy?[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]After all, I'm the one asking you all to attempt the impossible when taking part in these "club activities."[n][w][e]

[msg MSG_056_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1092 0 0][uf 4 23 1 2 3 25 25]"Asking" us, huh...[n][w][e]

[msg MSG_056_3_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0]...What's the matter?[n][w][e]

[msg MSG_056_5_0 [Yukari Takeba]]
[s][uf 4 5 2 4 65535 65535 0 0][uf 4 23 1 2 4 25 25]Oh, um... Nothing.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 3 25 25]C'mon, Leader. We've beaten them, so let's move on. Hurry, clock's ticking![n][w][e]

[msg MSG_057_0_00 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5011 0 0]Gatekeeper eliminated. No other Shadow activity detected in the vicinity.[n][w][e]

[msg MSG_058_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 4 23 1 5 1 25 25]Roger that. Seems like we'll be able to take a small breather here.[n][w][e]

[msg MSG_059_0_00 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 4 23 1 4 1 25 25][uf 4 23 1 5 0 25 25]You sure look happy today, Mitsuru.[n][w][e]
[s][uf 4 5 4 1 65535 65535 0 0]Let me guess: you had a lot of stress pent up from being stuck as support this whole time?[n][w][e]

[msg MSG_060_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4035 0 0][uf 4 23 1 5 1 25 25]Not at all. I was just thinking about how Yamagishi sounded so dependable.[n][w][e]

[msg MSG_061_0_00 [Fuuka Yamagishi]]
[s][uf 4 5 6 4 65535 50 0 0][uf 4 23 1 4 0 25 25][uf 4 23 1 5 0 25 25]...Huh? I do?[n][w][e]

[msg MSG_062_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0]The connection is stable, and you accurately predict the Shadows' locations, too.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]You're exactly what we need. Don't you think so too, [uf 4 1]?[n][w][e]

[sel SEL_063_0_00 top]
[s]She's a huge help.[e]
[s]I miss your voice, though.[e]

[msg MSG_064_0_00 [Fuuka Yamagishi]]
[s][uf 4 5 6 4 65535 50 0 0][uf 3 1 3 0 65535 5035 0 0]Y-You're exaggerating... Right now, I'm just trying to keep up with everyone.[n][w][e]
[s][uf 4 5 6 0 65535 50 0 0]But... I'll do my best to meet your expectations![n][w][e]

[msg MSG_065_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0][uf 4 23 1 5 1 25 25]Heh, even though I'm speaking right now? Though I should be glad you didn't say I was annoying.[n][w][e]
[s][uf 4 5 5 1 65535 65535 0 0]...But if you were to put me on the front lines, I'd certainly give you an earful.[n][w][e]

[msg MSG_066_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 4 23 1 5 0 25 25]...Now that we're all rested, shall we keep going?[n][w][e]

[msg MSG_067_0_00 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Okay, I've got your back, so let's move out once everyone's ready.[n][w][e]

[msg MSG_068_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2074 0 0]Hey, [uf 4 2], you've been at this nonstop, right?[n][w][e]

[msg MSG_069_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0]Isn't that because [uf 4 1]-kun is the leader?[n][w][e]

[msg MSG_070_0_00 [Junpei Iori]]
[s][uf 4 5 3 2 65535 65535 0 0][uf 4 23 1 3 2 25 25]Well, we're all a team, so we can't just let him shoulder everything himself.[n][w][e]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]Shouldn't we have someone step up to the plate whenever he takes a break? Say... like a second?[n][w][e]

[sel SEL_073_0_00 top]
[s]That's a good idea.[e]
[s]But we're doing just fine.[e]
[s]Whatever.[e]

[msg MSG_074_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2026 0 0]I know, right? I'm brilliant![n][w][e]
[s][bup 5 201 0 0]So if we had to pick his right-hand man, then it'd obviously be me, since I was the first one to bring it up![n][w][e]

[msg MSG_075_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25][uf 4 23 1 3 0 25 25]You didn't even let the rest of us get a word in... I bet you were angling for this from the beginning, huh?[n][w][e]

[msg MSG_076_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1060 0 0][uf 4 23 1 3 0 25 25]Yeah, I think so too. Plus, I feel like I can always count on [uf 4 1]-kun... unlike someone else.[n][w][e]

[msg MSG_076_5_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]...Yo, why you gotta look at me when you say that!? This is blatant favoritism![n][w][e]

[msg MSG_077_0_00 [Junpei Iori]]
[s][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2073 0 0][uf 4 23 1 3 2 25 25]Dang, ice cold! C'mon, man, I was just thinkin' about what'd be best for you...[n][w][e]

[msg MSG_077_5_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]Yeah, right... You were actually just thinking about yourself. It was so obvious.[n][w][e]

[msg MSG_078_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 3 0 25 25]Anyway, if [uf 4 1]-kun wanted to rest, he can just take a break from exploring.[n][w][e]

[msg MSG_078_5_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 3 3 25 25]Oh... Huh, yeah. I guess that's true.[n][w][e]
[s][uf 4 5 3 2 65535 65535 0 0][uf 4 23 1 3 2 25 25]But still, if you need a hand, I'll be happy to switch with you anytime, [uf 4 2]. Sleep on it, alright?[n][w][e]

[msg MSG_079_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2088 0 0][uf 4 23 1 3 1 25 25]Booyah, nailed it! Now all the ladies say, "Yeeeah!"[n][w][e]
[s][bup 5 201 0 0]Man, if everyone could see me now, girls would be all over me...[n][w][e]
[s][bup 5 201 0 0][uf 4 23 1 3 0 25 25]...But I guess that's not possible with the two of you around.[n][w][e]

[msg MSG_080_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]Ain't that right, my fellow Yakushima Rejects?[n][w][e]

[msg MSG_081_0_00 [Akihiko Sanada]]
[s][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3119 0 0][uf 4 23 1 4 2 25 25]Don't give us such a weird nickname! I wasn't interested in picking up girls in the first place.[n][w][e]

[msg MSG_082_0_00 [Junpei Iori]]
[s][bup 5 201 0 0]Welp, it's just good to know that nobody's perfect—not even Sanada-san.[n][w][e]
[s][bup 5 201 0 0][uf 4 23 1 4 0 25 25]I feel like the three of us got a lot closer that day... Don't you feel it, too?[n][w][e]

[sel SEL_083_0_00 top]
[s]Our bond grew stronger.[e]
[s]Sanada's not perfect?[e]
[s]But I'm different from you.[e]

[msg MSG_084_0_00 [Akihiko Sanada]]
[s][uf 4 5 4 3 65535 65535 0 0][uf 3 1 3 0 65535 3122 0 0][uf 4 23 1 3 0 25 25][uf 4 23 1 4 3 25 25]Hey... Are you sure you want to be lumped in together with Junpei?[n][w][e]

[msg MSG_085_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]Hey, whaddaya mean by that!? Ain't it great we're getting along?[n][w][e]

[msg MSG_086_0_00 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2071 0 0][uf 4 23 1 3 0 25 25][uf 4 23 1 4 0 25 25]What? Did you want him to be?[n][w][e]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 3 3 25 25]If he were, then we'd just be two extras leeching off of his spotlight.[n][w][e]

[msg MSG_087_0_00 [Akihiko Sanada]]
[s][uf 4 5 4 6 65535 65535 0 0][uf 4 23 1 4 3 25 25]...Don't you have any pride?[n][w][e]

[msg MSG_088_0_00 [Akihiko Sanada]]
[s][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3091 0 0][uf 4 23 1 3 0 25 25][uf 4 23 1 4 2 25 25]Wha—? Are you talking about Aigis? That doesn't count! It's not fair play![n][w][e]

[msg MSG_089_0_00 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 2 3 25 25]Senpai, you're, like, dead serious, huh...? I guess a better word would be "real competitive."[n][w][e]

[msg MSG_089_5_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25][uf 4 23 1 4 0 25 25]But, hey, it's still summer! Meaning we got time to redeem ourselves, so why don't we sneak out at night or something and—
[n][w][e]

[msg MSG_090_0_00 [Fuuka Yamagishi]]
[s][uf 4 5 6 3 65535 50 0 0][uf 3 1 3 0 65535 5003 0 0][uf 4 23 1 3 0 25 25]U-Um...[n][w][e]
[s][uf 4 5 6 6 65535 50 0 0]We can hear everything you've said... Yukari-chan and Kirijo-senpai, too.[n][w][e]

[msg MSG_091_0_00 [Akihiko Sanada]]
[s][uf 4 5 4 2 65535 65535 0 0][uf 3 1 3 0 65535 3127 0 0][uf 4 23 1 4 2 25 25]...That's enough small talk! Let's move out![n][w][e]

[msg MSG_092_0_00 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Confirmed annihilation of enemy Shadow... We are victorious.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Koromaru-san performed excellently as well. Once we return, we are to give you a reward, correct?[n][w][e]

[msg MSG_093_0_00 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][w][e]

[msg MSG_094_0_00 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]What would best suffice as a reward for Koromaru-san?[n][w][e]

[sel SEL_095_0_00 top]
[s]A delicious snack.[e]
[s]A gentle brushing.[e]
[s]He'll have to wait first.[e]

[msg MSG_096_0_00 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8004 0 0][uf 4 23 1 9 1 25 25]*pant* *pant*[n][w][e]

[msg MSG_097_0_00 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]Koromaru-san, you are drooling.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Koromaru-san is exuberant. Perhaps he is "one hungry boy," as they say.[n][w][e]

[msg MSG_098_0_00 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0][uf 4 23 1 9 1 25 25]Arf! Arf![n][w][e]

[msg MSG_099_0_00 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]Koromaru-san says that he was concerned about the current state of his coat.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Please do maintenance for him when you have the time.[n][w][e]

[msg MSG_100_0_00 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8012 0 0]Arf, arf![n][w][e]

[msg MSG_101_0_00 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]Koromaru-san says, in response to your heartless words, that he will continue to do his best.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Is this what they call... the carrot and the whip?[n][w][e]

[msg MSG_101_5_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 4 23 1 9 0 25 25]Well then, let us be off.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]I will also perform to the best of my ability in order to secure Koromaru-san the best possible reward.[n][w][e]

[msg MSG_101_7_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][w][e]

[msg MSG_102_0_00 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7001 0 0]So everyone up until now has defeated lots of enemies like the one just now, right?[n][w][e]
[s][uf 4 5 8 0 65535 65535 0 0]When fighting enemies stronger than you... is there anything important to keep in mind?[n][w][e]

[sel SEL_103_0_00 top]
[s]First, keep a level head.[e]
[s]Determination is key.[e]
[s]Well, there's a lot.[e]

[msg MSG_104_0_00 [Ken Amada]]
[s][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7061 0 0][uf 4 23 1 8 3 25 25]In other words... stay calm? Like the blue ranger?[n][w][e]

[msg MSG_105_0_00 [Ken Amada]]
[s][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0][uf 4 23 1 8 3 25 25]Then... you're telling me to be bold, like the black ranger?[n][w][e]

[msg MSG_106_0_00 [Ken Amada]]
[s][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0][uf 4 23 1 8 3 25 25]That's true... But I have to train more and get stronger. There's not much time...[n][w][e]

[msg MSG_107_0_00 [Fuuka Yamagishi]]
[s][uf 4 5 6 3 65535 50 0 0][uf 4 23 1 8 0 25 25]Amada-kun, there's no need to be worried. It's fine to start out slow and steady.[n][w][e]

[msg MSG_108_0_00 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0]Um... I appreciate your concern, but...[n][w][e]

[msg MSG_109_0_00 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9069 0 0]If he's saying he wants to get stronger, then let him do what he wants.[n][w][e]

[msg MSG_110_0_00 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 4 23 1 8 4 25 25]He's long made up his mind. Since he's here and all.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]...Ain't that right?[n][w][e]

[msg MSG_110_5_0 [Ken Amada]]
[s][uf 4 5 8 2 65535 65535 0 0][uf 4 23 1 8 2 25 25]Y-Yes...![n][w][e]

[msg MSG_110_7_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9081 0 0][uf 4 23 1 8 0 25 25]There you have it. If you're really worried about him, then back him up.[n][w][e]

[msg MSG_111_0_00 [Fuuka Yamagishi]]
[s][uf 4 5 6 4 65535 50 0 0]U-Understood...![n][w][e]
[s][uf 4 5 6 0 65535 50 0 0]Sorry, Amada-kun... Just let me know if you have trouble with anything.[n][w][e]

[msg MSG_112_0_00 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]Yes, of course! Thank you so much! I really do appreciate your support![n][w][e]

[msg MSG_113_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1119 0 0]Looks like we're about to reach the 200th floor... Just how tall is this place?[n][w][e]

[msg MSG_114_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0]At the very least, there should be an end. As for when we'll get there? We'll just have to keep climbing and find out.[n][w][e]
[s][uf 4 5 5 1 65535 65535 0 0][uf 4 23 1 5 1 25 25]...What's wrong, Yukari? Are you tired?[n][w][e]

[msg MSG_115_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25][uf 4 23 1 5 0 25 25]Ahaha, does it look like I'm dying? Well, I'm just raring to go, be it 300 or 400 floors![n][w][e]

[sel SEL_116_0_00 top]
[s]That's encouraging.[e]
[s]Let's get through this.[e]
[s]300 floors? No thanks.[e]

[msg MSG_117_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4024 0 0][uf 4 23 1 5 1 25 25]It truly is. I've a thing or two to learn from you about perseverance.[n][w][e]

[msg MSG_118_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0]Wait a second... Is that supposed to be a compliment? But you're the same way, Mitsuru-senpai.[n][w][e]

[msg MSG_119_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0][uf 4 23 1 5 1 25 25]That's right. All we need is for Yukari to whip everyone into shape.[n][w][e]

[msg MSG_120_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0]Yeah, no, I'm not doing that.[n][w][e]

[msg MSG_121_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4132 0 0][uf 4 23 1 5 1 25 25]Heh, I know how you feel, but Yukari might get on your case, you know?[n][w][e]

[msg MSG_122_0_00 [Yukari Takeba]]
[s][bup 2 201 0 0]Geez, Mitsuru-senpai... You're making me out to be a total witch, but I think I'd be nicer than you.[n][w][e]

[msg MSG_122_5_00 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25][uf 4 23 1 5 0 25 25]Well then, wanna keep going, [uf 4 1]-kun? Maybe we'll discover something.[n][w][e]

[msg MSG_123_0_00 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0]Yukari's right. Let's keep advancing, even if only a step at a time.[n][w][e]

[msg MSG_000_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1086 0 0][uf 4 23 1 2 1 25 25]Hey, nice work out there, [uf 4 1]. You're seriously leader material.[n][w][e]

[sel SEL_001_0_0 top]
[s]Naturally.[e]
[s]I just got lucky.[e]
[s]Wanna give it a try?[e]

[msg MSG_002_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1095 0 0]Haha, well, aren't you oozing with confidence? But honestly, that's a reassuring trait to see in a leader.[n][w][e]

[msg MSG_003_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1104 0 0]Yeah? Well, you know what they say: luck is just another word for skill.[n][w][e]

[msg MSG_004_0_0 [Yukari Takeba]]
[s][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1099 0 0][uf 4 23 1 2 4 25 25]Who, me? Uh, yeah, no thanks. I'd be in way over my head.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]Unlike you, I'd just drop the ball when push comes to shove. I lose my cool way too easily.[n][w][e]

[msg MSG_005_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25]Anyway, should we get going? After you, Leader.[n][w][e]

[msg MSG_006_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1114 0 0]Nice work. These Gatekeeper guys are super tough, huh?[n][w][e]
[s][bup 2 201 0 0]Might be time to call it a day. What do you think?[n][w][e]

[sel SEL_007_0_0 top]
[s]Yeah, let's head back.[e]
[s]I'm just getting started.[e]
[s]Do you wanna head back?[e]

[msg MSG_008_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1025 0 0][uf 4 23 1 2 1 25 25]Cool! Let's head to the entrance.[n][w][e]

[msg MSG_009_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1107 0 0][uf 4 23 1 2 1 25 25]Well, someone's motivated. Okay, let's see how far we can get, then.[n][w][e]

[msg MSG_010_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1062 0 0]Oh, no, that's not what I meant. I'm not tired. I just figured this might be a good stopping point.[n][w][e]
[s][bup 2 201 0 0]But I'm sure you have this expedition all planned out, so it's your call.[n][w][e]

[msg MSG_011_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1062 0 0]Whew, now we can get through.[n][w][e]
[s][bup 2 201 0 0]We're on a roll, but what do you think, [uf 4 1]-kun? Wanna keep going?[n][w][e]

[sel SEL_012_0_0 top]
[s]Yeah, let's keep it up.[e]
[s]Let's stop here.[e]
[s]You sound motivated.[e]

[msg MSG_013_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1116 0 0][uf 4 23 1 2 1 25 25]You got it! You think we'll make it to the next Gatekeeper?[n][w][e]

[msg MSG_014_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1068 0 0][uf 4 23 1 2 1 25 25]Oh, are you tired? These Gatekeepers sure are a handful, aren't they?[n][w][e]

[msg MSG_015_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1061 0 0][uf 4 23 1 2 6 25 25]Well, yeah, I guess so... But that makes me sound like I'm usually not.[n][w][e]

[msg MSG_016_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25]Anyway, you ready to go?[n][w][e]

[msg MSG_017_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1114 0 0]Not too long ago, I don't think we would've stood a chance against an enemy that tough.[n][w][e]
[s][bup 2 201 0 0]Don't you think we've gotten even stronger...?[n][w][e]

[sel SEL_018_0_0 top]
[s]Of course.[e]
[s]There's room to improve.[e]
[s]Don't get carried away.[e]

[msg MSG_019_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1096 0 0][uf 4 23 1 2 1 25 25]Haha, thanks for the vote of confidence. That's real encouraging, coming from you.[n][w][e]
[s][bup 2 201 0 0]When we first started out, it took everything I had just to summon my Persona.[n][w][e]

[msg MSG_020_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1122 0 0][uf 4 23 1 2 6 25 25]Geez, would it kill you to compliment a girl every once in a while?[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25]Kiiidding. Honestly, I prefer constructive criticism.[n][w][e]

[msg MSG_021_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1025 0 0]Yeah, of course. We're not the only ones getting stronger.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]I won't let it go to my head, unlike a certain someone we both know.[n][w][e]

[msg MSG_022_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]Okay, let's keep moving. On to the next?[n][w][e]

[msg MSG_023_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1086 0 0][uf 4 23 1 2 1 25 25]Phew... We won. Feels like I'm at the top of my game today.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]Maybe it's because my horoscope said that Libras are supposed to be really lucky today?[n][w][e]

[sel SEL_024_0_0 top]
[s]Yeah, I think so.[e]
[s]That's unrelated.[e]
[s]I'll read your palm, too.[e]

[msg MSG_025_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1095 0 0][uf 4 23 1 2 1 25 25]Haha, so you're the type to buy into superstitions? I totally get it. Like, you're skeptical, but they'll stay at the back of your mind.[n][w][e]

[msg MSG_026_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1119 0 0][uf 4 23 1 2 6 25 25]Yeah, I'm with you there. If only things were that simple...[n][w][e]

[msg MSG_027_0_0 [Yukari Takeba]]
[s][uf 4 5 2 4 65535 65535 0 0][uf 3 1 3 0 65535 1099 0 0][uf 4 23 1 2 4 25 25]Really? I never took you as the type to be interested in—
[n][w][e]
[s][uf 4 5 2 2 65535 65535 0 0][uf 4 23 1 2 2 25 25]Hey... Is this some kinda ploy where you try to hold my hand?[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 6 25 25]Oh, who am I kidding...? You're no Junpei.[n][w][e]

[msg MSG_028_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]Well, they say luck is a skill, right? So it wouldn't hurt to believe in good omens...[n][w][e]

[msg MSG_029_0_0 [Yukari Takeba]]
[s][uf 4 5 2 4 65535 65535 0 1][uf 4 23 1 2 4 25 25]Wait... Has the date changed already?[n][w][e]

[msg MSG_030_0_0 [Yukari Takeba]]
[s][uf 4 5 2 4 65535 65535 0 1]Do horoscopes change during the Dark Hour!? Ugh... The curiosity is killing me.[n][w][e]

[msg MSG_031_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2088 0 0][uf 4 23 1 3 1 25 25]Awww yeah, who's da man!?[n][w][e]
[s][bup 5 201 0 0]I guess you weren't too shabby either. Keep up the good work, bud.[n][w][e]

[sel SEL_032_0_0 top]
[s]Oh, gee. Thanks.[e]
[s]Someone's on an ego trip.[e]
[s]Same goes for you, man.[e]

[msg MSG_033_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2029 0 0]Remember, my dude, in times like these, teamwork is key.[n][w][e]

[msg MSG_034_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2036 0 0]Haha, I'm just tryin' to hype you up, man. Don't worry, you're still the one callin' the shots.[n][w][e]

[msg MSG_035_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2026 0 0]Hey, man, I got your back, so let's keep sharing the load.[n][w][e]

[msg MSG_036_0_0 [Junpei Iori]]
[s][bup 5 201 0 0]Alright, let's roll![n][w][e]

[msg MSG_037_0_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2115 0 0][uf 4 23 1 3 3 25 25]Phew... These guys are a serious workout compared to your average Shadow.[n][w][e]
[s][uf 4 5 3 3 65535 65535 0 0]I mean, I've still got gas in the tank, but how 'bout we make a quick pitstop?[n][w][e]

[sel SEL_038_0_0 top]
[s]Yeah, let's go back.[e]
[s]Not right now.[e]
[s]You sure you're not tired?[e]

[msg MSG_039_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2095 0 0][uf 4 23 1 3 1 25 25]Heheh, gotta know when to cash in your chips, am I right?[n][w][e]
[s][bup 5 201 0 0]C'mon, I'll race ya to the nearest teleporter. On your marks... Get set... GO!!![n][w][e]

[msg MSG_040_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2099 0 0][uf 4 23 1 3 4 25 25]Whaaat? For reals? Well, aren't you an overachiever.[n][w][e]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 3 3 25 25]Whatever. I'll keep you company, dude.[n][w][e]

[msg MSG_041_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2085 0 0][uf 4 23 1 3 4 25 25]Whoa there, h-hold up... I was worried YOU were running on empty, not me.[n][w][e]
[s][uf 4 5 3 3 65535 65535 0 0][uf 4 23 1 3 3 25 25]But if you're gonna keep going, I got your back. Just don't push it, alright?[n][w][e]

[msg MSG_042_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2096 0 0][uf 4 23 1 3 1 25 25]Aaand that's a wrap, folks.[n][w][e]
[s][bup 5 201 0 0]Damn, look at us go. Nothing can stop us now! Execution Squad, move out![n][w][e]

[sel SEL_043_0_0 top]
[s]Let's get going.[e]
[s]Let's turn back.[e]
[s]All the way to the top.[e]

[msg MSG_044_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2108 0 0]Glad to see you brought your A game. Between you and me, we've got the next fight in the bag.[n][w][e]

[msg MSG_045_0_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2101 0 0][uf 4 23 1 3 3 25 25]Hold up... You're seriously calling it quits?[n][w][e]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]Welp, I guess this is as good a time as any for an intermission. The second half of the Junpei Spectacular can always wait for next time.[n][w][e]

[msg MSG_046_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2110 0 0]Ambitious, ain'tcha? Not that I got a problem with that![n][w][e]

[msg MSG_047_0_0 [Junpei Iori]]
[s][bup 5 201 0 0]Alright, let's bounce.[n][w][e]

[msg MSG_048_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2111 0 0]Is it just me, or are these Shadows upping their game? How much stronger are they gonna get?[n][w][e]

[sel SEL_049_0_0 top]
[s]I don't wanna know.[e]
[s]No clue.[e]
[s]We just gotta up our game, too.[e]

[msg MSG_050_0_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2115 0 0][uf 4 23 1 3 3 25 25]For real. Maybe they don't even have a limit, but we just gotta bust through 'em.[n][w][e]

[msg MSG_051_0_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2115 0 0][uf 4 23 1 3 3 25 25]Well, we can forget about things getting easier down the line...[n][w][e]

[msg MSG_052_0_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2115 0 0][uf 4 23 1 3 3 25 25]Yeah, sure, but that's easier said than done, y'know?[n][w][e]

[msg MSG_053_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]And, hey, don't get me wrong. I ain't scared of 'em or anything, alright?[n][w][e]
[s][uf 4 5 3 2 65535 65535 0 0][uf 4 23 1 3 2 25 25]Heck, I'm hashin' out big plans to finish 'em off in style as we speak...[n][w][e]

[msg MSG_054_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]Yo, what's with that look? You don't believe me?[n][w][e]

[msg MSG_055_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2086 0 0][uf 4 23 1 3 1 25 25]Whew... Man, we totally crushed it.[n][w][e]
[s][uf 4 5 3 9 65535 65535 0 0][uf 4 23 1 3 9 25 25]In baseball terms, you could say the team ace, Iori, pitched a complete game and totally shut out the opponent.[n][w][e]

[sel SEL_056_0_0 top]
[s]I don't get it.[e]
[s]This isn't baseball.[e]
[s]But I'm the ace.[e]

[msg MSG_057_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2075 0 0][uf 4 23 1 3 1 25 25]Okay, let me put it this way: I was the cleanup hitter, and I hit the ball outta the park to score us that huge win.[n][w][e]

[msg MSG_058_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2132 0 0][uf 4 23 1 3 4 25 25]'Course it's not! Ever heard of an analogy?[n][w][e]

[msg MSG_059_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2110 0 0][uf 4 23 1 3 1 25 25]Ooh, look at you, talkin' big. But there's enough room in the Hall of Fame for the two of us.[n][w][e]

[msg MSG_060_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]Anyway, the bottom line is that you need a team with powerful batters and a strong bullpen in order to—
[n][w][e]
[s][bup 5 201 0 0][uf 4 23 1 3 4 25 25]Wait, what were we talkin' about again?[n][w][e]

[msg MSG_061_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3086 0 0]Good going, [uf 4 1]![n][w][e]
[s][uf 4 5 4 0 65535 65535 0 0]Your directions were on point, and you managed to keep your cool against a tough opponent.[n][w][e]

[sel SEL_062_0_0 top]
[s]You bet I did.[e]
[s]Not necessarily.[e]
[s]It was rough.[e]

[msg MSG_063_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3106 0 0][uf 4 23 1 4 1 25 25]Heh, all right, hotshot. I see we're in good hands.[n][w][e]

[msg MSG_064_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3094 0 0][uf 4 23 1 4 1 25 25]Haha, so you wore a poker face the whole time? That's brilliant.[n][w][e]

[msg MSG_065_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3088 0 0][uf 4 23 1 4 1 25 25]What, being humble in front of your senpai?[n][w][e]
[s][uf 4 5 4 0 65535 65535 0 0][uf 4 23 1 4 0 25 25]Just remember, seniority means nothing on the battlefield, so don't hold back.[n][w][e]

[msg MSG_066_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 4 23 1 4 0 25 25]All right, time to move on. Stay sharp.[n][w][e]

[msg MSG_067_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3085 0 0]Great. Now we'll be able to move on.[n][w][e]
[s][uf 4 5 4 0 65535 65535 0 0]There's always the option to turn back, too. What's your call, [uf 4 1]?[n][w][e]

[sel SEL_068_0_0 top]
[s]Let's head back.[e]
[s]Let's keep going.[e]
[s]Let me think about it.[e]

[msg MSG_069_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]Got it. Let's regroup for now.[n][w][e]

[msg MSG_070_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]Gotcha. We'll take things at your pace.[n][w][e]

[msg MSG_071_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3113 0 0]No worries, go ahead. Take your time to assess the situation—there's no need to rush.[n][w][e]

[msg MSG_072_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3086 0 0]Great, the path is clear.[n][w][e]
[s][uf 4 5 4 9 65535 65535 0 0][uf 4 23 1 4 9 25 25]So what's the plan? I'm down to knock out the next Gatekeeper if you want.[n][w][e]

[sel SEL_073_0_0 top]
[s]Let's go for it.[e]
[s]I don't know about that...[e]
[s]Let me think about it.[e]

[msg MSG_074_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 9 65535 65535 0 0][uf 3 1 3 0 65535 3108 0 0]That's the spirit. I'm willing to stick it out for the long haul if you are.[n][w][e]

[msg MSG_075_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3045 0 0][uf 4 23 1 4 1 25 25]Why? What's up? You tired?[n][w][e]
[s][uf 4 5 4 1 65535 65535 0 0]It's fine. There's no reason you should have to force yourself to press forward. Our opponents aren't going anywhere.[n][w][e]

[msg MSG_076_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3028 0 0]Sure, go for it. I'm still good to go.[n][w][e]

[msg MSG_077_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 4 23 1 4 0 25 25]All right, let's get moving. We're counting on you.[n][w][e]

[msg MSG_078_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3002 0 0][uf 4 23 1 4 1 25 25]That last opponent sure packed a punch. It made for a good fight.[n][w][e]
[s][uf 4 5 4 0 65535 65535 0 0][uf 4 23 1 4 0 25 25]The tougher the opponent, the more pumped up you get. Don't you agree?[n][w][e]

[sel SEL_079_0_0 top]
[s]Yeah, I get you.[e]
[s]I prefer them weaker.[e]
[s]Depends on the situation.[e]

[msg MSG_080_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 9 65535 65535 0 0][uf 3 1 3 0 65535 3025 0 0][uf 4 23 1 4 9 25 25]Glad we see eye-to-eye. After all, the only way to get stronger is by pushing your limits.[n][w][e]

[msg MSG_081_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3047 0 0][uf 4 23 1 4 1 25 25]Really? Hm... I guess taking care of those weaker opponents could be good training.[n][w][e]

[msg MSG_082_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3028 0 0][uf 4 23 1 4 0 25 25]Fair point. You won't glean much from fighting an opponent way out of your league.[n][w][e]
[s][uf 4 5 4 0 65535 65535 0 0]But sometimes, facing off against a heavyweight might get you to the next level.[n][w][e]

[msg MSG_083_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 4 23 1 4 0 25 25]Now then... Care to find out what's waiting for us up ahead?[n][w][e]

[msg MSG_084_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3108 0 0]No matter how many times I see you fight, I still can't believe my eyes.[n][w][e]
[s][uf 4 5 4 0 65535 65535 0 0]Just how on earth are you swapping your Personas out at will?[n][w][e]

[sel SEL_085_0_0 top]
[s]I was surprised at first, too.[e]
[s]I hear it's rare.[e]
[s]Want me to lend you one?[e]

[msg MSG_086_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3106 0 0]You say that, but you've taken to it like a fish to water. You know, I think there's something special about you.[n][w][e]

[msg MSG_087_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3027 0 0]I suppose you are kind of an oddball, in a manner of speaking.[n][w][e]
[s][uf 4 5 4 0 65535 65535 0 0]But you can't be the only one... I'm sure someone else out there has the same ability as you.[n][w][e]

[msg MSG_088_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 3 1 3 0 65535 3131 0 0][uf 4 23 1 4 1 25 25]Haha, I appreciate the offer, but I already have my hands full training with the one I've got.[n][w][e]

[msg MSG_089_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 4 23 1 4 0 25 25]At any rate, having you around has opened us up to more battle strategies, so let's keep capitalizing on that.[n][w][e]

[msg MSG_090_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4107 0 0]Excellent—a perfect victory. All thanks to your precise orders, [uf 4 1].[n][w][e]

[sel SEL_091_0_0 top]
[s]That went well.[e]
[s]I'm just getting started.[e]
[s]This is exhausting.[e]

[msg MSG_092_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4113 0 0][uf 4 23 1 5 1 25 25]I'm sure it's tough to lead the team, but evidently, you're quite up to the task.[n][w][e]

[msg MSG_093_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4106 0 0][uf 4 23 1 5 1 25 25]I admire your tenacity. That kind of drive will lead to further growth.[n][w][e]

[msg MSG_094_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4131 0 0][uf 4 23 1 5 1 25 25]Indeed it is. Fulfilling the role of a leader requires both mind and matter.[n][w][e]

[msg MSG_095_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 4 23 1 5 0 25 25]Of course, I'll try to help out wherever I can. That said, please don't act recklessly.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]Now then, let's get back to business.[n][w][e]

[msg MSG_096_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4112 0 0]Somehow, we pulled through. Those Gatekeepers are truly a cut above the rest.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]This would be an ideal time to regroup, but what say you?[n][w][e]

[sel SEL_097_0_0 top]
[s]Let's head back.[e]
[s]I'd like to keep going.[e]
[s]I'm not sure.[e]

[msg MSG_098_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4115 0 0]Fine by me. It's best to be prepared for all possible contingencies.[n][w][e]

[msg MSG_099_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4113 0 0][uf 4 23 1 5 1 25 25]I take it you want to ride the momentum to seize our next victory? Very well. I'll leave it to your discretion.[n][w][e]

[msg MSG_100_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4065 0 0]Fair enough. There's no rule of thumb for when to retreat.[n][w][e]
[s][uf 4 5 5 1 65535 65535 0 0][uf 4 23 1 5 1 25 25]Whatever you choose, I'll stand by your decision. Lead on.[n][w][e]

[msg MSG_101_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4085 0 0]Now then, the path is clear. Shall we proceed?[n][w][e]

[sel SEL_102_0_0 top]
[s]Of course.[e]
[s]Let's head back.[e]
[s]If we're all able.[e]

[msg MSG_103_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4113 0 0][uf 4 23 1 5 1 25 25]You seem to be in fine form tonight. Very well, let's get back to work.[n][w][e]

[msg MSG_104_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4113 0 0]All right. Then let's make for the entrance.[n][w][e]

[msg MSG_105_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4113 0 0][uf 4 23 1 5 1 25 25]Of course. That's no problem at all.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0][uf 4 23 1 5 0 25 25]I can rest easy with you at the reins. Keep up the good work.[n][w][e]

[msg MSG_106_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4112 0 0]How many Gatekeepers does that make? They're becoming more ferocious by the minute, aren't they?[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]It's likely you'll face greater tactical challenges moving forward, but I trust you'll be fine.[n][w][e]

[sel SEL_107_0_0 top]
[s]Leave it to me.[e]
[s]I don't know...[e]
[s]Not much of a choice.[e]

[msg MSG_108_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4039 0 0]Needless to say, we'll do our utmost to support you.[n][w][e]

[msg MSG_109_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4045 0 0][uf 4 23 1 5 1 25 25]Well, I know you can handle it. Don't doubt yourself, just keep doing what you've been doing.[n][w][e]

[msg MSG_110_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 1 65535 65535 0 0][uf 3 1 3 0 65535 4024 0 0][uf 4 23 1 5 1 25 25]I'm afraid not, but trust me, you're more than capable. And I'll support you as best I can.[n][w][e]

[msg MSG_111_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 4 23 1 5 0 25 25]Shall we keep going, then?[n][w][e]

[msg MSG_112_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4112 0 0]We'll be able to progress now, but... how high do you suppose this tower is?[n][w][e]

[sel SEL_113_0_0 top]
[s]No idea.[e]
[s]We might be close.[e]
[s]No use dwelling on it.[e]

[msg MSG_114_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4028 0 0]I believe we still have a long road ahead of us, but part of our job is to find out for certain.[n][w][e]

[msg MSG_115_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]I wish that was true, but from the looks of things, we've still a ways to go.[n][w][e]

[msg MSG_116_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4027 0 0]That's true. But one thing we can be certain of is that, come what may, we will eventually reach our goal.[n][w][e]

[msg MSG_117_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0]...I'm not losing my nerve, of course, mind you.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]Having made it this far is a remarkable feat in itself.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]For now, let's keep paving a path forward.[n][w][e]

[msg MSG_118_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Enemy Shadow annihilated. You possess superlative decision-making skills, [uf 4 2]-san.[n][w][e]

[sel SEL_119_0_0 top]
[s]That went well.[e]
[s]It was just luck.[e]
[s]You did great, Aigis.[e]

[msg MSG_120_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Yes, learning that team coordination is equally as important as individual strengths has proved insightful.[n][w][e]

[msg MSG_121_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6037 0 0]The odds of an operation being streamlined by chance is astronomically low. I suspect you are being modest, as per usual.[n][w][e]

[msg MSG_122_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0]Thank you. That battle was "easy-peasy lemon squeezy," as they say.[n][w][e]

[msg MSG_123_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]Now, let us resume our exploration.[n][w][e]

[msg MSG_124_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]High-level threat eliminated. How is everyone's current condition?[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]If you are experiencing fatigue, then I recommend we return early.[n][w][e]

[sel SEL_125_0_0 top]
[s]Let's head back for tonight.[e]
[s]I can keep going.[e]
[s]Doesn't matter to me.[e]

[msg MSG_126_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Understood. Then let us return to the entrance.[n][w][e]

[msg MSG_127_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]That is very "magnifique," as they say. Then let us resume our exploration.[n][w][e]

[msg MSG_128_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]This is the time to be decisive. As such, you must make the final call, [uf 4 2]-san.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Whatever you decide, I shall be at your side.[n][w][e]

[msg MSG_129_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Gatekeeper Shadow eliminated. While this may be a good stopping point...[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Should we press forward instead?[n][w][e]

[sel SEL_130_0_0 top]
[s]Sure.[e]
[s]I wanna go home.[e]
[s]You're raring to go.[e]

[msg MSG_131_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Understood. In that case, let us "roll n' rock," as they say.[n][w][e]

[msg MSG_132_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]I see. Very well. Let us return and recuperate in preparation for our next battle.[n][w][e]

[msg MSG_133_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6030 0 0]Of course. This is my mission, after all.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Well then, [uf 4 2]-san, shall we?[n][w][e]

[msg MSG_134_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Threat eliminated. Mission complete.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Which reminds me: have you adjusted to Shifting and using Theurgy in battle?[n][w][e]

[sel SEL_135_0_0 top]
[s]To a certain extent.[e]
[s]I haven't had to.[e]
[s]It's like second nature.[e]

[msg MSG_136_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Both are useful in battle. It would be for the best if you were to utilize them more efficiently.[n][w][e]

[msg MSG_137_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6058 0 0]I see. In other words, you have yet to utilize them in battle.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Is this what they call "saving the best for last"? Your potential truly is limitless.[n][w][e]

[msg MSG_138_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]I expected nothing less from [uf 4 2]-san. Your mastery of tactics is second to none.[n][w][e]

[msg MSG_139_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]I will also fight without restraining my power. The upcoming battles will surely test our strength.[n][w][e]

[msg MSG_140_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Cleanup operation, complete. Enemies of this caliber are like sitting kappa.[n][w][e]

[sel SEL_141_0_0 top]
[s]You got that right.[e]
[s]Not really.[e]
[s]...Why "kappa"?[e]

[msg MSG_142_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Oh, good. Perhaps the kappa will be happy for us as well.[n][w][e]

[msg MSG_143_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0]Right, they were not sitting, were they? I should have said they were like "standing kappa" instead. Idioms are difficult.[n][w][e]

[msg MSG_144_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]I was informed it is an idiom that describes an easy or defenseless target.[n][w][e]

[msg MSG_145_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]By the way... what manner of creature is Mr. Kappa? I would like to meet him one day.[n][w][e]

[msg MSG_146_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6008 0 0]Enemy Shadow eliminated. That was a well-orchestrated attack, [uf 4 2]-san.[n][w][e]

[sel SEL_147_0_0 top]
[s]That went well.[e]
[s]It was just luck.[e]
[s]You did great, Aigis.[e]

[msg MSG_148_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6027 0 0][uf 4 23 1 7 1 25 25]Yes, a well-coordinated team is essential to achieving victory, isn't it?[n][w][e]

[msg MSG_149_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6131 0 0][uf 4 23 1 7 1 25 25]Hehe, you're always so modest, [uf 4 2]-san.[n][w][e]

[msg MSG_150_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6039 0 0][uf 4 23 1 7 1 25 25]Thank you. I just want to do what I can to best fulfill my role.[n][w][e]

[msg MSG_151_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 4 23 1 7 0 25 25]Now then, let's resume our exploration.[n][w][e]

[msg MSG_152_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6087 0 0]Mission accomplished. Is anyone hurt?[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]If you feel tired, please don't push yourself too hard and head back instead.[n][w][e]

[sel SEL_153_0_0 top]
[s]Let's turn back for now.[e]
[s]I can keep going.[e]
[s]You're very composed.[e]

[msg MSG_154_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6025 0 0]Understood. Let's make for the first floor.[n][w][e]

[msg MSG_155_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6025 0 0][uf 4 23 1 7 1 25 25]Roger that! We want to ride this momentum, correct?[n][w][e]

[msg MSG_156_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6027 0 0][uf 4 23 1 7 1 25 25]They do say, "Haste makes waste." It's all right to take your time to weigh all your options.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0][uf 4 23 1 7 0 25 25]The decision is yours, [uf 4 2]-san. I trust you.[n][w][e]

[msg MSG_157_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6009 0 0]Great job, everyone. Now, we could stop here...[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]But I think we can keep going. What do you think?[n][w][e]

[sel SEL_158_0_0 top]
[s]Sounds like a plan.[e]
[s]I wanna go home.[e]
[s]You're raring to go.[e]

[msg MSG_159_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6025 0 0][uf 4 23 1 7 1 25 25]Yes! Let's rock n' roll, then![n][w][e]

[msg MSG_160_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6107 0 0]Understood. Then let's head back to the entrance.[n][w][e]

[msg MSG_161_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6118 0 0][uf 4 23 1 7 1 25 25]Of course! I want to do all that I can, fighting alongside everyone else.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0][uf 4 23 1 7 0 25 25]Please lead on, [uf 4 2]-san.[n][w][e]

[msg MSG_162_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6115 0 0]Well done.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Whether Shift or Theurgy, you're proficient in every tactic at your disposal now, aren't you?[n][w][e]

[sel SEL_163_0_0 top]
[s]To a certain extent.[e]
[s]It's like second nature.[e]
[s]I'm not sure.[e]

[msg MSG_164_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6131 0 0][uf 4 23 1 7 1 25 25]You're not one to brag, are you, [uf 4 2]-san? Hehe, we're fortunate to have you.[n][w][e]

[msg MSG_165_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6131 0 0][uf 4 23 1 7 1 25 25]Hehe, we're fortunate to have you.[n][w][e]

[msg MSG_166_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6061 0 0][uf 4 23 1 7 1 25 25]You've made it this far, so I think you're allowed to be confident in yourself. Don't you?[n][w][e]

[msg MSG_167_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0]I'll also prepare myself for our final battle.[n][w][e]

[msg MSG_168_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6087 0 0]We took them down easily. They were practically sitting kappa.[n][w][e]

[sel SEL_169_0_0 top]
[s]You got that right.[e]
[s]Not really.[e]
[s]...Why "kappa"?[e]

[msg MSG_170_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6132 0 0][uf 4 23 1 7 1 25 25]Hehe, no offense to Mr. Kappa, but the expression is a bit amusing, isn't it?[n][w][e]

[msg MSG_171_0_0 [Aigis]]
[s][uf 4 5 7 3 65535 65535 0 0][uf 3 1 3 0 65535 6073 0 0][uf 4 23 1 7 3 25 25]Oh? Should I have said "standing kappa" instead...? Idioms are difficult.[n][w][e]

[msg MSG_172_0_0 [Aigis]]
[s][uf 4 5 7 1 65535 65535 0 0][uf 3 1 3 0 65535 6060 0 0][uf 4 23 1 7 1 25 25]Junpei-san taught me that idiom. It describes an easy or defenseless target.[n][w][e]

[msg MSG_173_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 4 23 1 7 0 25 25]By the way... what kind of creature is Mr. Kappa? I'd love to meet him one day.[n][w][e]

[msg MSG_174_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7011 0 0][uf 4 23 1 8 1 25 25]Nice! We took out a tough enemy.[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0]That win was all thanks to your instructions, [uf 4 1]-san![n][w][e]

[sel SEL_175_0_0 top]
[s]Naturally.[e]
[s]Not quite.[e]
[s]It was all you.[e]

[msg MSG_176_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]It was really impressive.[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0]The leader has to issue precise orders for the team to function properly.[n][w][e]

[msg MSG_177_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0]Haha, well, of course everyone contributes by combining all our individual strengths as well.[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0]But the leader is the one who puts all the pieces together. And you're good at it, too.[n][w][e]

[msg MSG_178_0_0 [Ken Amada]]
[s][uf 4 5 8 4 65535 65535 0 0][uf 3 1 3 0 65535 7037 0 0][uf 4 23 1 8 4 25 25]Really? I'm happy you think so, but...[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]I think I'm a lot stronger fighting alongside everyone.[n][w][e]

[msg MSG_179_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0]Oh, sorry. That kinda came out of nowhere.[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0]It's just that I've always felt this way, so I wanted to tell you myself.[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0]Anyway, let's keep this up.[n][w][e]

[msg MSG_180_0_0 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7115 0 0]Phew, these Gatekeepers are a lot tougher than the typical Shadow wandering around.[n][w][e]
[s][uf 4 5 8 0 65535 65535 0 0]Should we keep going? Or is it time we take a break?[n][w][e]

[sel SEL_181_0_0 top]
[s]Let's turn back.[e]
[s]Let's move on.[e]
[s]I'm on the fence.[e]

[msg MSG_182_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7132 0 0][uf 4 23 1 8 1 25 25]Good idea. Let's head back to the entrance, then.[n][w][e]

[msg MSG_183_0_0 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7108 0 0]I see... You're a man of steel, aren't you, [uf 4 1]-san?[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]Oh, but I'm also good to go! Let's see how far we can get.[n][w][e]

[msg MSG_184_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]This is a good stopping point, so it's hard to decide, huh?[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0]Well, just let me know when you've made up your mind. I'm fine either way.[n][w][e]

[msg MSG_185_0_0 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7087 0 0]...I think I had a small breakthrough during that last fight.[n][w][e]
[s][uf 4 5 8 0 65535 65535 0 0]Is it okay if we keep going? I'd like to reinforce what I picked up while it's still fresh.[n][w][e]

[sel SEL_186_0_0 top]
[s]Sure, let's do it.[e]
[s]Let's head back first.[e]
[s]I'll think about it.[e]

[msg MSG_187_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7116 0 0][uf 4 23 1 8 1 25 25]Thank you. I'll do my best to make myself useful.[n][w][e]

[msg MSG_188_0_0 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7069 0 0]Oh, are you tired?[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]Okay, that's fine. We can just pick up from here next time.[n][w][e]

[msg MSG_189_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0][uf 4 23 1 8 1 25 25]I trust your decision, but if we can carry on, then let's.[n][w][e]

[msg MSG_190_0_0 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7115 0 0]How many Gatekeeper Shadows do you think there are total?[n][w][e]
[s][uf 4 5 8 3 65535 65535 0 0][uf 4 23 1 8 3 25 25]They keep getting tougher, which means there could be some really strong ones waiting for us up ahead.[n][w][e]

[sel SEL_191_0_0 top]
[s]Yeah, probably.[e]
[s]I hope that was the last of them.[e]
[s]No point dwelling on it.[e]

[msg MSG_192_0_0 [Ken Amada]]
[s][uf 4 5 8 2 65535 65535 0 0][uf 3 1 3 0 65535 7090 0 0][uf 4 23 1 8 2 25 25]If that's the case... then I'll be ready.[n][w][e]

[msg MSG_193_0_0 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7063 0 0][uf 4 23 1 8 0 25 25]If only... That'd be nice, but in the end, it's just wishful thinking.[n][w][e]

[msg MSG_194_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7120 0 0][uf 4 23 1 8 1 25 25]That's true. We should just focus on the enemies in front of us.[n][w][e]

[msg MSG_195_0_0 [Ken Amada]]
[s][uf 4 5 8 2 65535 65535 0 0][uf 4 23 1 8 2 25 25]I need to train harder so that I can be ready to face any foe, no matter how strong they might be.[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]Okay, let's move on.[n][w][e]

[msg MSG_196_0_0 [Ken Amada]]
[s][uf 4 5 8 0 65535 65535 0 0][uf 3 1 3 0 65535 7088 0 0]Phew, there we go. Glad that's over.[n][w][e]
[s][uf 4 5 8 0 65535 65535 0 0]These Gatekeepers sure are tough. Imagine if every enemy on a floor was a Gatekeeper.[n][w][e]

[sel SEL_197_0_0 top]
[s]Yeah, let's not.[e]
[s]It'd be good experience.[e]
[s]We'd just steamroll them.[e]

[msg MSG_198_0_0 [Ken Amada]]
[s][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7120 0 0][uf 4 23 1 8 3 25 25]Haha, I know I'm the one who brought it up, but thinking about it sent a shiver down my spine.[n][w][e]

[msg MSG_199_0_0 [Ken Amada]]
[s][uf 4 5 8 3 65535 65535 0 0][uf 3 1 3 0 65535 7120 0 0]Yeah, it'd definitely keep us on our toes... Then again, we're always on edge.[n][w][e]

[msg MSG_200_0_0 [Ken Amada]]
[s][uf 4 5 8 4 65535 65535 0 0][uf 3 1 3 0 65535 7103 0 0][uf 4 23 1 8 4 25 25]Huh? You really think so!? [uf 4 1]-san, you sound super confident![n][w][e]
[s][uf 4 5 8 3 65535 65535 0 0][uf 4 23 1 8 3 25 25]Meanwhile, I'm getting chills just picturing it.[n][w][e]

[msg MSG_201_0_0 [Ken Amada]]
[s][uf 4 5 8 2 65535 65535 0 0][uf 4 23 1 8 2 25 25]There's no knowing what kind of tricks they have up their sleeve. Let's stay alert.[n][w][e]

[msg MSG_202_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][w][e]

[msg MND_203_0_0]
[s]Koromaru seems happy we won.[n][w][e]

[msg MSG_204_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0]Arf![n][w][e]

[sel SEL_205_0_0 top]
[s]Good boy.[e]
[s]I'll give you a treat later, okay?[e]
[s]Keep up the good work.[e]

[msg MSG_206_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8012 0 0]Arf, arf![n][w][e]

[msg MND_207_0_0]
[s]Koromaru looks proud of himself.[n][w][e]

[msg MSG_208_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0]Arf![n][w][e]

[msg MSG_209_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8009 0 0]*pant* *pant*[n][w][e]

[msg MND_210_0_0]
[s]Koromaru seems to be panting heavily.[n][w][e]
[s]Did that last battle wear him out?[n][w][e]

[msg MSG_211_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0]*whine*[n][w][e]

[sel SEL_212_0_0 top]
[s]Let's turn back.[e]
[s]Let's go a little further.[e]
[s]Let me assess the situation.[e]

[msg MSG_213_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][w][e]

[msg MND_214_0_0]
[s]Koromaru seems to be on board.[n][w][e]
[s]Heading back is probably the right idea...[n][w][e]

[msg MSG_215_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]...Arf! Arf, arf![n][w][e]

[msg MND_216_0_0]
[s]Looks like Koromaru is psyching himself up.[n][w][e]
[s]He seems willing to go the extra mile...[n][w][e]

[msg MSG_217_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Arf![n][w][e]

[msg MND_218_0_0]
[s]Koromaru seems to be on board.[n][w][e]
[s]It's up to me to decide whether[n]we forge ahead or pull back...[n][w][e]

[msg MSG_219_0_0 [Koromaru]]
[s][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8007 0 0][uf 4 23 1 9 1 25 25]Awoooooo![n][w][e]

[msg MND_220_0_0]
[s]Koromaru is in a good mood.[n][w][e]

[msg MSG_221_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 4 23 1 9 0 25 25]Arf![n][w][e]

[sel SEL_222_0_0 top]
[s]Want to keep going?[e]
[s]Let's head back.[e]
[s]We're on a roll, yeah?[e]

[msg MSG_223_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Woof![n][w][e]

[msg MND_224_0_0]
[s]Koromaru seems determined.[n][w][e]

[msg MSG_225_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8004 0 0]Arf![n][w][e]

[msg MND_226_0_0]
[s]Koromaru seems to be on board.[n][w][e]

[msg MSG_227_0_0 [Koromaru]]
[s][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0][uf 4 23 1 9 1 25 25]Arf! Arf![n][w][e]

[msg MND_228_0_0]
[s]Koromaru seems determined.[n][w][e]

[msg MSG_229_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 4 23 1 9 0 25 25]Arf![n][w][e]

[msg MSG_230_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8008 0 0]Arf![n][w][e]

[msg MSG_231_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Nice work. You too, Koro-chan.[n][w][e]
[s][uf 4 5 6 0 65535 50 0 0]Since the enemies are getting stronger, we'll need to be even more cautious moving forward.[n][w][e]

[sel SEL_232_0_0 top]
[s]We'll be fine.[e]
[s]I'm a little nervous.[e]
[s]You got this, Koromaru.[e]

[msg MSG_233_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0]Arf, arf![n][w][e]

[msg MSG_234_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Heehee, are you feeling confident too, Koro-chan? Looks like there's courage aplenty here.[n][w][e]

[msg MSG_235_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8012 0 0]Arf, arf![n][w][e]

[msg MSG_236_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Koro-chan's cheering you on. He's got your back![n][w][e]

[msg MSG_237_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0][uf 3 1 3 0 65535 8010 0 0]Arf![n][w][e]

[msg MSG_238_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Heehee, looks like someone's full of spirit. We'll be counting on you, Koro-chan.[n][w][e]

[msg MSG_239_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0]Arf, arf![n][w][e]

[msg MSG_240_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5011 0 0]The Gatekeeper has been defeated! Thanks for all your hard work, everyone.[n][w][e]

[msg MSG_241_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0]Arf![n][w][e]

[msg MSG_242_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0]I know I'm just stating the obvious here, but Koro-chan sure is amazing, isn't he?[n][w][e]
[s][uf 4 5 6 0 65535 50 0 0]He's so cooperative and a great team-player. It's almost like he understands everything we say.[n][w][e]

[sel SEL_243_0_0 top]
[s]Because he's a smart boy.[e]
[s]Maybe it's your imagination?[e]
[s]Atta boy, Koromaru.[e]

[msg MSG_244_0_0 [Koromaru]]
[s][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8001 0 0][uf 4 23 1 9 1 25 25]Arf, arf![n][w][e]

[msg MSG_245_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Heehee, Koro-chan looks so happy. See? He does understand.[n][w][e]

[msg MSG_246_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 6 65535 50 0 0][uf 3 1 3 0 65535 5037 0 0]N-No, it can't be. You understand us, don't you, Koro-chan?[n][w][e]

[msg MSG_247_0_0 [Koromaru]]
[s][uf 4 5 9 3 65535 65535 0 0][uf 4 23 1 9 3 25 25]*whine*[n][w][e]

[msg MSG_248_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 6 65535 50 0 0]See? Look how sad he is. I'm sure he understands what we're saying.[n][w][e]

[msg MSG_249_0_0 [Koromaru]]
[s][uf 4 5 9 1 65535 65535 0 0][uf 3 1 3 0 65535 8012 0 0][uf 4 23 1 9 1 25 25]Arf, arf![n][w][e]

[msg MSG_250_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Heehee, Koro-chan looks so happy. See? He does understand.[n][w][e]

[msg MSG_251_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0][uf 4 23 1 9 0 25 25]Keep up the good work, Koro-chan![n][w][e]

[msg MSG_252_0_0 [Koromaru]]
[s][uf 4 5 9 0 65535 65535 0 0]Arf, arf![n][w][e]

[msg MSG_253_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9049 0 0]Looks like we're done here...[n][w][e]

[msg MSG_254_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0]You're better than I thought. I can see why Aki hyped you up.[n][w][e]

[sel SEL_255_0_0 top]
[s]Thanks, I guess.[e]
[s]That was no big deal.[e]
[s]You're no pushover yourself.[e]

[msg MSG_256_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9024 0 0]I got your back, so do what you gotta do.[n][w][e]

[msg MSG_257_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9098 0 0]Heh, best to stay humble. Pride's just gonna get you killed.[n][w][e]

[msg MSG_258_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9102 0 0]...Well, yeah. I can't afford to be holding back either.[n][w][e]

[msg MSG_259_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0]Let's get going.[n][w][e]

[msg MSG_260_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9101 0 0]There goes that pain in the neck.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]Want to call it here?[n][w][e]

[sel SEL_261_0_0 top]
[s]Yeah, let's leave.[e]
[s]I'd rather keep going.[e]
[s]What should we do?[e]

[msg MSG_262_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9107 0 0]Smart. Head back and rest or whatever to get ready for the next trip.[n][w][e]

[msg MSG_263_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9108 0 0]Gotcha. Well, you're the leader. I'll just stick with you.[n][w][e]

[msg MSG_264_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9070 0 0]Up to you. Just don't bite off more than you can chew.[n][w][e]

[msg MSG_265_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9126 0 0]Alright, path looks clear.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]We're gonna keep goin', right?[n][w][e]

[sel SEL_266_0_0 top]
[s]Yeah, of course.[e]
[s]Maybe we should go back...[e]
[s]You seem fired up.[e]

[msg MSG_267_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 1 65535 65535 0 0][uf 3 1 3 0 65535 9098 0 0][uf 4 23 1 10 1 25 25]Heh, glad we're on the same page. I've got plenty of fuel to burn myself.[n][w][e]

[msg MSG_268_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9057 0 0]That's fine. This ain't a bad stopping point either.[n][w][e]

[msg MSG_269_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9102 0 0]...Nah, I'm just checkin' with you.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]'Course, I ain't feelin' too bad myself.[n][w][e]

[msg MSG_270_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 4 23 1 10 0 25 25]Let's go.[n][w][e]

[msg MSG_271_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9104 0 0]Stubborn bastard, wasn't it? No match for us, though.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]There are gonna be even tougher fights down the road, so be ready for that.[n][w][e]

[sel SEL_272_0_0 top]
[s]You can count on me.[e]
[s]I can take 'em.[e]
[s]I'll leave it to you.[e]

[msg MSG_273_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9069 0 0]Don't mean to put you on the spot or anything, but our victory's ridin' on you.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]Let's see you get it done, Leader.[n][w][e]

[msg MSG_274_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 1 65535 65535 0 0][uf 3 1 3 0 65535 9049 0 0][uf 4 23 1 10 1 25 25]Hmph, you got nerve, I'll give you that.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0][uf 4 23 1 10 0 25 25]A little bravado's fine, but don't get too cocky or it'll bite you in the ass.[n][w][e]

[msg MSG_275_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9056 0 0][uf 4 25 10]......[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]Hey, don't go passing the baton to me. There's no guarantee I'll always be around, you know.[n][w][e]

[msg MSG_276_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0]Alright, let's get going.[n][w][e]

[msg MSG_277_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9107 0 0]...Glad that's over.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]Don't go wastin' your time on these kinda enemies.[n][w][e]

[sel SEL_278_0_0 top]
[s]Let's kick it into gear.[e]
[s]No need to be hasty.[e]
[s]You feeling burned out?[e]

[msg MSG_279_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9024 0 0]Be my guest.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]I dunno how big this place is, but can't hurt to try and make some progress.[n][w][e]

[msg MSG_280_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9049 0 0]...Fair.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]But can't hurt to try and make some progress either, especially when I'm in the mood.[n][w][e]

[msg MSG_281_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0][uf 3 1 3 0 65535 9114 0 0]What, would you tell me off if I were? I ain't made of glass, so worry about yourself.[n][w][e]
[s][uf 4 5 10 0 65535 65535 0 0]I'll do my job, and I'll do it damn well. So rest easy and do yours.[n][w][e]

[msg MSG_282_0_0 [Shinjiro Aragaki]]
[s][uf 4 5 10 0 65535 65535 0 0]C'mon, let's move out.[n][w][e]

[msg MSG_283_0_0 [Junpei Iori]]
[s][uf 4 5 3 2 65535 65535 0 0][uf 3 1 3 0 65535 2062 0 0][uf 4 23 1 2 2 25 25]Hmmm...[n][w][e]

[msg MSG_284_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 3 65535 50 0 0]What's wrong, Junpei-kun? Something on your mind?[n][w][e]

[msg MSG_285_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 2 0 25 25]Nah, it's nothing, just... You know those Shadows with books on their heads?[n][w][e]
[s][bup 5 201 0 0]Like the one we fought just now? What's even written inside that book?[n][w][e]

[msg MSG_286_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 4 65535 50 0 0]Oh, I was wondering the same thing...[n][w][e]
[s][uf 4 5 6 0 65535 50 0 0]We'll catch glimpses from time to time, but it's hard to tell while fighting.[n][w][e]

[msg MSG_287_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2026 0 0][uf 4 23 1 2 1 25 25]Right? I mean, I don't give a crap about the words...[n][w][e]
[s][bup 5 201 0 0]But if there are photo collections of pretty models, like in manga magazines, then...[n][w][e]

[msg MSG_288_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0][uf 3 1 3 0 65535 4061 0 0]Have you ever wondered how those scale-shaped Shadows stand upright?[n][w][e]

[msg MSG_289_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0]Ah, the balance types. I imagine they'd struggle with standing upright and moving around.[n][w][e]

[msg MSG_290_0_0 [Mitsuru Kirijo]]
[s][uf 4 5 5 0 65535 65535 0 0]Do you suppose there's a reason they look the way they do?[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]Moreover... I'm actually quite tempted to tip them over.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]...Apologies, I digress.[n][w][e]
[s][uf 4 5 5 0 65535 65535 0 0]Let's move along, Leader.[n][w][e]

[msg MSG_291_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6012 0 0]Enemy defeated. Requesting our next directive.[n][w][e]

[sel SEL_292_0_0 top]
[s]Let's keep exploring.[e]
[s]Let's turn back for today.[e]
[s]What would you like to do?[e]

[msg MSG_293_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Affirmative. Though Tartarus may be a colossal tower...[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]With constant, incremental progress, we will gradually reach our objective.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]A journey of a thousand miles begins by first treading without fear, as they say.[n][w][e]

[msg MSG_294_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6024 0 0]Understood. Better safe than sorry, as they say.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]They also say, "Haste makes waste," and, "Slow and steady wins the race."[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Though... is it not more optimal to be fast and steady instead?[n][w][e]

[msg MSG_295_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0][uf 3 1 3 0 65535 6058 0 0]...I had not anticipated a query in response to my query.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Is this what they call "getting blindsided"?[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]But I do not have any blind side to speak of, so does this not apply to me?[n][w][e]

[msg MSG_296_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 4 65535 50 0 0]A-Aigis, you sure know some unusual phrases. Where did you learn about them?[n][w][e]

[msg MSG_297_0_0 [Aigis]]
[s][uf 4 5 7 0 65535 65535 0 0]I have a daily academic regimen.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]Just the other day, Junpei-san taught me how to write haikus.[n][w][e]
[s][uf 4 5 7 0 65535 65535 0 0]"Oh my Tartarus... Dark, decrepit Tartarus... Why are you so tall?"[n][w][e]

[msg MSG_298_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3085 0 0]Great. Now we'll be able to progress.[n][w][e]

[msg MSG_299_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0]What do you think, [uf 4 1]? Any concerns moving forward?[n][w][e]

[sel SEL_300_0_0 top]
[s]None at all.[e]
[s]Just a few.[e]
[s]Should I be concerned?[e]

[msg MSG_301_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3131 0 0]That confidence of yours sure is reassuring. I'm sure everyone else on the team thinks so, too.[n][w][e]

[msg MSG_302_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0]Keep it up. I'll back you up in any way I can.[n][w][e]

[msg MSG_303_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3093 0 0]Ah... I understand where you're coming from.[n][w][e]

[msg MSG_304_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0]But you're doing great. Don't panic, keep moving forward, and you'll be fine.[n][w][e]

[msg MSG_305_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0][uf 3 1 3 0 65535 3060 0 0]Well, we've been on the front lines for some time now...[n][w][e]

[msg MSG_306_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 0 65535 65535 0 0]So I just wanted to remind you to reach out if you ever need anything.[n][w][e]

[msg MSG_307_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0]Sanada-senpai...[n][w][e]
[s][uf 4 5 6 1 65535 50 0 0]You seem... calmer than before. It's a really welcome change.[n][w][e]

[msg MSG_308_0_0 [Akihiko Sanada]]
[s][uf 4 5 4 1 65535 65535 0 0][uf 4 23 1 4 1 25 25]Heh, you just had to add that last bit. A "welcome change," huh?[n][w][e]
[s][uf 4 5 4 1 65535 65535 0 0]Anyway, let's get going. We still have a long road ahead of us.[n][w][e]

[msg MSG_309_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5002 0 0]How does it feel to be back in action, Amada-kun?[n][w][e]

[msg MSG_310_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]Great, actually. Thanks for asking, Fuuka-san.[n][w][e]

[msg MSG_311_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0]I'd like to thank you as well, [uf 4 1]-san—for letting me on the front lines.[n][w][e]
[s][uf 4 5 8 2 65535 65535 0 0][uf 4 23 1 8 2 25 25]I want to get even stronger so I can help make things easier on everyone else.[n][w][e]

[sel SEL_312_0_0 top]
[s]Looking forward to it.[e]
[s]You're plenty strong already.[e]
[s]We'll help you out, too.[e]

[msg MSG_313_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7040 0 0][uf 4 23 1 8 1 25 25]Just watch me. I promise I'll follow through.[n][w][e]

[msg MSG_314_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7052 0 0][uf 4 23 1 8 1 25 25]Haha, I don't need any spoiling, you know? Besides, I'm a growing boy.[n][w][e]

[msg MSG_315_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0][uf 3 1 3 0 65535 7026 0 0][uf 4 23 1 8 1 25 25]Thank you, I appreciate it.[n][w][e]

[msg MSG_316_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]By the way, Amada-kun... I caught a glimpse of you from behind just now.[n][w][e]
[s][uf 4 5 6 1 65535 50 0 0]I think you might have gotten taller.[n][w][e]

[msg MSG_317_0_0 [Ken Amada]]
[s][uf 4 5 8 4 65535 65535 0 0][uf 4 23 1 8 4 25 25]Really!?[n][w][e]
[s][uf 4 5 8 1 65535 65535 0 0][uf 4 23 1 8 1 25 25]Maybe it's because of all the milk I drink, hehe.[n][w][e]

[msg MSG_318_0_0 [Ken Amada]]
[s][uf 4 5 8 1 65535 65535 0 0]Okay, [uf 4 1]-san. Shall we get going?[n][w][e]

[msg MSG_319_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5011 0 0]Enemy Shadow eliminated.[n][w][e]

[msg MSG_320_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25]Way to go, everyone. Let's keep it up, and—
[n][w][e]

[msg MSG_321_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 4 65535 50 0 0]Oh, hold that thought, Yukari-chan...[n][w][e]
[s][uf 4 5 6 0 65535 50 0 0]Are those... blisters on your hands?[n][w][e]

[msg MSG_322_0_0 [Yukari Takeba]]
[s][uf 4 5 2 4 65535 65535 0 0][uf 4 23 1 2 4 25 25]Wha— How could you tell!?[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]Yeah... They're just a little bit blistered. I can still shoot just fine, though.[n][w][e]

[sel SEL_323_0_0 top]
[s]Nice catch, Fuuka.[e]
[s]Don't push yourself, Yukari.[e]
[s]Shall we take a break?[e]

[msg MSG_324_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5061 0 0]Um... I just noticed you seemed a little different from usual.[n][w][e]
[s][uf 4 5 6 1 65535 50 0 0]I have bandages and other first aid stuff, so let me know if you need anything, okay, Yukari-chan?[n][w][e]

[msg MSG_325_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I agree. Fortunately, it doesn't seem too bad right now.[n][w][e]
[s][uf 4 5 6 1 65535 50 0 0]But I can wrap your hands with some bandages if the blisters are bothering you.[n][w][e]

[msg MSG_326_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0][uf 3 1 3 0 65535 5062 0 0]I think we should. Fortunately, it doesn't seem too bad right now.[n][w][e]
[s][uf 4 5 6 1 65535 50 0 0]But if you do take a break, I'll keep an eye on the perimeter for you.[n][w][e]

[msg MSG_327_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25]Gotcha. Thanks, Fuuka.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25][uf 4 25 2]......[n][w][e]
[s][bup 2 201 0 0]I get this feeling you've been looking out for us more than usual lately.[n][w][e]

[msg MSG_328_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 4 65535 50 0 0]R-Really? I'm glad I could at least do that much.[n][w][e]
[s][uf 4 5 6 1 65535 50 0 0]After all, my role here is to support everyone.[n][w][e]
[s][uf 4 5 6 1 65535 50 0 0]Well, shall we get going, Leader?[n][w][e]

[msg MSG_329_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1116 0 0]Great. Now we can keep moving.[n][w][e]

[msg MSG_330_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0]Even if the theory about defeating the Shadows that appear during a full moon turns out to be wrong...[n][w][e]
[s][bup 2 201 0 0]I'm sure there's something here that can help us get rid of the Dark Hour.[n][w][e]

[sel SEL_331_0_0 top]
[s]I think so, too.[e]
[s]What if there's nothing?[e]
[s]Only one way to find out.[e]

[msg MSG_332_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1028 0 0][uf 4 23 1 2 6 25 25]Honestly, I'd be surprised if there wasn't anything at all...[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]At this point, all we can do is find out for ourselves—especially since this is a job only we can do.[n][w][e]

[msg MSG_333_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1095 0 0][uf 4 23 1 2 1 25 25]Haha, that'd seriously suck. But even if we swing and miss, it's not like we have anything to lose, right?[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]If there's nothing at all, then we've eliminated one possibility. That means we just have to start looking somewhere else.[n][w][e]

[msg MSG_334_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 3 1 3 0 65535 1095 0 0][uf 4 23 1 2 1 25 25]Haha, I'm glad you're so motivated, [uf 4 1]-kun.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]It's definitely best to get as far as we can rather than sit around, mulling over hypotheticals.[n][w][e]

[msg MSG_335_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 0 65535 50 0 0]It's incredible you always find a silver lining, Yukari-chan.[n][w][e]

[msg MSG_336_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0][uf 4 23 1 2 1 25 25]Honestly, half of it is probably just me putting up a front, but the other half is thanks to you, Fuuka.[n][w][e]
[s][bup 2 201 0 0][uf 4 23 1 2 0 25 25]Thank you for giving me that recording.[n][w][e]

[msg MSG_337_0_0 [Fuuka Yamagishi]]
[s][uf 4 5 6 1 65535 50 0 0]Yukari-chan...[n][w][e]

[msg MSG_338_0_0 [Yukari Takeba]]
[s][bup 2 201 0 0]All right! Time to get going! Lead the way, [uf 4 1]-kun.[n][w][e]

[msg MSG_339_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2086 0 0][uf 4 23 1 3 1 25 25]Everyone, line up! Since we're on a roll, how 'bout we put the pedal to the metal?[n][w][e]

[sel SEL_340_0_0 top]
[s]You're on fire.[e]
[s]Let's take it slow.[e]
[s]Let's turn back.[e]

[msg MSG_341_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 3 1 3 0 65535 2095 0 0]Damn right I am. Figured just mopin' around wasn't gonna get me anywhere.[n][w][e]

[msg MSG_342_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 0 25 25]We'll get some answers eventually, so why not fight here while we wait? At least we'll get stronger.[n][w][e]
[s][bup 5 201 0 0]Sometimes you just gotta look at the bright side and do what you gotta do, y'know?[n][w][e]

[msg MSG_343_0_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2123 0 0][uf 4 23 1 3 3 25 25]You're totally missing my point, dude. I didn't mean getting faster, I meant getting psyched up.[n][w][e]

[msg MSG_344_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 0 25 25]Rather than think about this or that, we've got more to gain from knocking down a Shadow or two, right?[n][w][e]
[s][bup 5 201 0 0]Sure, we're in the dark now, but things will work out on their own, trust me.[n][w][e]

[msg MSG_345_0_0 [Junpei Iori]]
[s][uf 4 5 3 3 65535 65535 0 0][uf 3 1 3 0 65535 2105 0 0][uf 4 23 1 3 3 25 25]Well, that's your call, but don't forget—sometimes you gotta ride the momentum.[n][w][e]

[msg MSG_346_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 0 25 25]Trust me, I totally get where you're coming from. One nasty plot twist, and we're suddenly back at square one.[n][w][e]
[s][bup 5 201 0 0]That said, I think we oughta put in effort to get stronger, so we'll be ready for anything.[n][w][e]

[msg MSG_347_0_0 [Junpei Iori]]
[s][bup 5 201 0 0][uf 4 23 1 3 1 25 25]Anyway, the choice is yours![n][w][e]
[s][bup 5 201 0 0]Whether we press on or pull back, I've got your back, dude.[n][w][e]

